import 'dart:io';

import 'package:jnigen/jnigen.dart';

void main(List<String> args) async {
  final packageRoot = Platform.script.resolve('../');

  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve('lib/src/android_bindings/package/'),
          structure: OutputStructure.packageStructure,
        ),
      ),
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        addGradleSources: true,
        androidExample: 'example/',
      ),
      sourcePath: [packageRoot.resolve('android/src/main/kotlin')],
      classes: [
        'android.webkit.WebView',
        'android.webkit.WebViewClient',
        'android.webkit.WebSettings',
        'android.print.PrintDocumentAdapter',
        'android.print.PrintAttributes',
        'android.print.PrintDocumentInfo',
        'android.print.PageRange',
        'android.os.ParcelFileDescriptor',
        'android.os.Bundle',
        'android.content.Context',
        'android.app.Activity',
        'android.view.View',
        'android.view.ViewGroup',
        'java.io.File',
        'java.io.File',
        'java.lang.Runnable',
        'com.example.native_pdf_engine.PdfPrinter',
      ],
      preamble: '// Generated by jnigen. Do not edit.\n',
    ),
  );
}
