// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../Canvas.dart' as canvas$_;

/// from: `android.graphics.pdf.PdfDocument$Page`
extension type PdfDocument$Page._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/graphics/pdf/PdfDocument$Page',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfDocument$Page> type = $PdfDocument$Page$Type$();
}

extension PdfDocument$Page$$Methods on PdfDocument$Page {
  static final _id_get$canvas = PdfDocument$Page._class.instanceMethodId(
    r'getCanvas',
    r'()Landroid/graphics/Canvas;',
  );

  static final _get$canvas =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.graphics.Canvas getCanvas()`
  /// The returned object must be released after use, by calling the [release] method.
  canvas$_.Canvas? get canvas {
    return _get$canvas(
      reference.pointer,
      _id_get$canvas.pointer,
    ).object<canvas$_.Canvas?>();
  }

  static final _id_get$info = PdfDocument$Page._class.instanceMethodId(
    r'getInfo',
    r'()Landroid/graphics/pdf/PdfDocument$PageInfo;',
  );

  static final _get$info =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.graphics.pdf.PdfDocument$PageInfo getInfo()`
  /// The returned object must be released after use, by calling the [release] method.
  PdfDocument$PageInfo? get info {
    return _get$info(
      reference.pointer,
      _id_get$info.pointer,
    ).object<PdfDocument$PageInfo?>();
  }
}

final class $PdfDocument$Page$Type$ extends jni$_.JType<PdfDocument$Page> {
  @jni$_.internal
  const $PdfDocument$Page$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/graphics/pdf/PdfDocument$Page;';
}

/// from: `android.graphics.pdf.PdfDocument$PageInfo$Builder`
extension type PdfDocument$PageInfo$Builder._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/graphics/pdf/PdfDocument$PageInfo$Builder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfDocument$PageInfo$Builder> type =
      $PdfDocument$PageInfo$Builder$Type$();
  static final _id_new$ = _class.constructorId(r'(III)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i, int i1, int i2)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PdfDocument$PageInfo$Builder(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
  ) {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      i,
      i1,
      i2,
    ).object<PdfDocument$PageInfo$Builder>();
  }
}

extension PdfDocument$PageInfo$Builder$$Methods
    on PdfDocument$PageInfo$Builder {
  static final _id_create = PdfDocument$PageInfo$Builder._class
      .instanceMethodId(
        r'create',
        r'()Landroid/graphics/pdf/PdfDocument$PageInfo;',
      );

  static final _create =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.graphics.pdf.PdfDocument$PageInfo create()`
  /// The returned object must be released after use, by calling the [release] method.
  PdfDocument$PageInfo? create() {
    return _create(
      reference.pointer,
      _id_create.pointer,
    ).object<PdfDocument$PageInfo?>();
  }

  static final _id_setContentRect = PdfDocument$PageInfo$Builder._class
      .instanceMethodId(
        r'setContentRect',
        r'(Landroid/graphics/Rect;)Landroid/graphics/pdf/PdfDocument$PageInfo$Builder;',
      );

  static final _setContentRect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.graphics.pdf.PdfDocument$PageInfo$Builder setContentRect(android.graphics.Rect rect)`
  /// The returned object must be released after use, by calling the [release] method.
  PdfDocument$PageInfo$Builder? setContentRect(jni$_.JObject? rect) {
    final _$rect = rect?.reference ?? jni$_.jNullReference;
    return _setContentRect(
      reference.pointer,
      _id_setContentRect.pointer,
      _$rect.pointer,
    ).object<PdfDocument$PageInfo$Builder?>();
  }
}

final class $PdfDocument$PageInfo$Builder$Type$
    extends jni$_.JType<PdfDocument$PageInfo$Builder> {
  @jni$_.internal
  const $PdfDocument$PageInfo$Builder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/graphics/pdf/PdfDocument$PageInfo$Builder;';
}

/// from: `android.graphics.pdf.PdfDocument$PageInfo`
extension type PdfDocument$PageInfo._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/graphics/pdf/PdfDocument$PageInfo',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfDocument$PageInfo> type =
      $PdfDocument$PageInfo$Type$();
}

extension PdfDocument$PageInfo$$Methods on PdfDocument$PageInfo {
  static final _id_get$contentRect = PdfDocument$PageInfo._class
      .instanceMethodId(r'getContentRect', r'()Landroid/graphics/Rect;');

  static final _get$contentRect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.graphics.Rect getContentRect()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get contentRect {
    return _get$contentRect(
      reference.pointer,
      _id_get$contentRect.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$pageHeight = PdfDocument$PageInfo._class
      .instanceMethodId(r'getPageHeight', r'()I');

  static final _get$pageHeight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getPageHeight()`
  core$_.int get pageHeight {
    return _get$pageHeight(
      reference.pointer,
      _id_get$pageHeight.pointer,
    ).integer;
  }

  static final _id_get$pageNumber = PdfDocument$PageInfo._class
      .instanceMethodId(r'getPageNumber', r'()I');

  static final _get$pageNumber =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getPageNumber()`
  core$_.int get pageNumber {
    return _get$pageNumber(
      reference.pointer,
      _id_get$pageNumber.pointer,
    ).integer;
  }

  static final _id_get$pageWidth = PdfDocument$PageInfo._class.instanceMethodId(
    r'getPageWidth',
    r'()I',
  );

  static final _get$pageWidth =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getPageWidth()`
  core$_.int get pageWidth {
    return _get$pageWidth(reference.pointer, _id_get$pageWidth.pointer).integer;
  }
}

final class $PdfDocument$PageInfo$Type$
    extends jni$_.JType<PdfDocument$PageInfo> {
  @jni$_.internal
  const $PdfDocument$PageInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/graphics/pdf/PdfDocument$PageInfo;';
}

/// from: `android.graphics.pdf.PdfDocument`
extension type PdfDocument._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/graphics/pdf/PdfDocument',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfDocument> type = $PdfDocument$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory PdfDocument() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<PdfDocument>();
  }
}

extension PdfDocument$$Methods on PdfDocument {
  static final _id_close = PdfDocument._class.instanceMethodId(
    r'close',
    r'()V',
  );

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void close()`
  void close() {
    _close(reference.pointer, _id_close.pointer).check();
  }

  static final _id_finishPage = PdfDocument._class.instanceMethodId(
    r'finishPage',
    r'(Landroid/graphics/pdf/PdfDocument$Page;)V',
  );

  static final _finishPage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void finishPage(android.graphics.pdf.PdfDocument$Page page)`
  void finishPage(PdfDocument$Page? page) {
    final _$page = page?.reference ?? jni$_.jNullReference;
    _finishPage(
      reference.pointer,
      _id_finishPage.pointer,
      _$page.pointer,
    ).check();
  }

  static final _id_get$pages = PdfDocument._class.instanceMethodId(
    r'getPages',
    r'()Ljava/util/List;',
  );

  static final _get$pages =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.List<android.graphics.pdf.PdfDocument$PageInfo> getPages()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<PdfDocument$PageInfo?>? get pages {
    return _get$pages(
      reference.pointer,
      _id_get$pages.pointer,
    ).object<jni$_.JList<PdfDocument$PageInfo?>?>();
  }

  static final _id_startPage = PdfDocument._class.instanceMethodId(
    r'startPage',
    r'(Landroid/graphics/pdf/PdfDocument$PageInfo;)Landroid/graphics/pdf/PdfDocument$Page;',
  );

  static final _startPage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.graphics.pdf.PdfDocument$Page startPage(android.graphics.pdf.PdfDocument$PageInfo pageInfo)`
  /// The returned object must be released after use, by calling the [release] method.
  PdfDocument$Page? startPage(PdfDocument$PageInfo? pageInfo) {
    final _$pageInfo = pageInfo?.reference ?? jni$_.jNullReference;
    return _startPage(
      reference.pointer,
      _id_startPage.pointer,
      _$pageInfo.pointer,
    ).object<PdfDocument$Page?>();
  }

  static final _id_writeTo = PdfDocument._class.instanceMethodId(
    r'writeTo',
    r'(Ljava/io/OutputStream;)V',
  );

  static final _writeTo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void writeTo(java.io.OutputStream outputStream)`
  void writeTo(jni$_.JObject? outputStream) {
    final _$outputStream = outputStream?.reference ?? jni$_.jNullReference;
    _writeTo(
      reference.pointer,
      _id_writeTo.pointer,
      _$outputStream.pointer,
    ).check();
  }
}

final class $PdfDocument$Type$ extends jni$_.JType<PdfDocument> {
  @jni$_.internal
  const $PdfDocument$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/graphics/pdf/PdfDocument;';
}
