// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.os.Bundle`
extension type Bundle._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/os/Bundle');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Bundle> type = $Bundle$Type$();
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator<android.os.Bundle> CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject? get CREATOR =>
      _id_CREATOR.getNullable(_class, jni$_.JObject.type) as jni$_.JObject?;

  static final _id_EMPTY = _class.staticFieldId(
    r'EMPTY',
    r'Landroid/os/Bundle;',
  );

  /// from: `static public final android.os.Bundle EMPTY`
  /// The returned object must be released after use, by calling the [release] method.
  static Bundle? get EMPTY =>
      _id_EMPTY.getNullable(_class, Bundle.type) as Bundle?;

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Bundle() {
    return _new$(_class.reference.pointer, _id_new$.pointer).object<Bundle>();
  }

  static final _id_new$1 = _class.constructorId(r'(Landroid/os/Bundle;)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.os.Bundle bundle)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Bundle.new$1(Bundle? bundle) {
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$bundle.pointer,
    ).object<Bundle>();
  }

  static final _id_new$2 = _class.constructorId(
    r'(Landroid/os/PersistableBundle;)V',
  );

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.os.PersistableBundle persistableBundle)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Bundle.new$2(jni$_.JObject? persistableBundle) {
    final _$persistableBundle =
        persistableBundle?.reference ?? jni$_.jNullReference;
    return _new$2(
      _class.reference.pointer,
      _id_new$2.pointer,
      _$persistableBundle.pointer,
    ).object<Bundle>();
  }

  static final _id_new$3 = _class.constructorId(r'(I)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Bundle.new$3(core$_.int i) {
    return _new$3(
      _class.reference.pointer,
      _id_new$3.pointer,
      i,
    ).object<Bundle>();
  }

  static final _id_new$4 = _class.constructorId(r'(Ljava/lang/ClassLoader;)V');

  static final _new$4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.ClassLoader classLoader)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Bundle.new$4(jni$_.JObject? classLoader) {
    final _$classLoader = classLoader?.reference ?? jni$_.jNullReference;
    return _new$4(
      _class.reference.pointer,
      _id_new$4.pointer,
      _$classLoader.pointer,
    ).object<Bundle>();
  }
}

extension Bundle$$Methods on Bundle {
  static final _id_clear = Bundle._class.instanceMethodId(r'clear', r'()V');

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void clear()`
  void clear() {
    _clear(reference.pointer, _id_clear.pointer).check();
  }

  static final _id_clone = Bundle._class.instanceMethodId(
    r'clone',
    r'()Ljava/lang/Object;',
  );

  static final _clone =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.Object clone()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? clone() {
    return _clone(
      reference.pointer,
      _id_clone.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_deepCopy = Bundle._class.instanceMethodId(
    r'deepCopy',
    r'()Landroid/os/Bundle;',
  );

  static final _deepCopy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.os.Bundle deepCopy()`
  /// The returned object must be released after use, by calling the [release] method.
  Bundle? deepCopy() {
    return _deepCopy(reference.pointer, _id_deepCopy.pointer).object<Bundle?>();
  }

  static final _id_describeContents = Bundle._class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int describeContents()`
  core$_.int describeContents() {
    return _describeContents(
      reference.pointer,
      _id_describeContents.pointer,
    ).integer;
  }

  static final _id_getBinder = Bundle._class.instanceMethodId(
    r'getBinder',
    r'(Ljava/lang/String;)Landroid/os/IBinder;',
  );

  static final _getBinder =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.os.IBinder getBinder(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getBinder(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getBinder(
      reference.pointer,
      _id_getBinder.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getBundle = Bundle._class.instanceMethodId(
    r'getBundle',
    r'(Ljava/lang/String;)Landroid/os/Bundle;',
  );

  static final _getBundle =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.os.Bundle getBundle(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  Bundle? getBundle(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getBundle(
      reference.pointer,
      _id_getBundle.pointer,
      _$string.pointer,
    ).object<Bundle?>();
  }

  static final _id_getByte = Bundle._class.instanceMethodId(
    r'getByte',
    r'(Ljava/lang/String;)B',
  );

  static final _getByte =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallByteMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public byte getByte(java.lang.String string)`
  core$_.int getByte(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getByte(
      reference.pointer,
      _id_getByte.pointer,
      _$string.pointer,
    ).byte;
  }

  static final _id_getByte$1 = Bundle._class.instanceMethodId(
    r'getByte',
    r'(Ljava/lang/String;B)Ljava/lang/Byte;',
  );

  static final _getByte$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public java.lang.Byte getByte(java.lang.String string, byte b)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JByte? getByte$1(jni$_.JString? string, core$_.int b) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getByte$1(
      reference.pointer,
      _id_getByte$1.pointer,
      _$string.pointer,
      b,
    ).object<jni$_.JByte?>();
  }

  static final _id_getByteArray = Bundle._class.instanceMethodId(
    r'getByteArray',
    r'(Ljava/lang/String;)[B',
  );

  static final _getByteArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public byte[] getByteArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JByteArray? getByteArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getByteArray(
      reference.pointer,
      _id_getByteArray.pointer,
      _$string.pointer,
    ).object<jni$_.JByteArray?>();
  }

  static final _id_getChar = Bundle._class.instanceMethodId(
    r'getChar',
    r'(Ljava/lang/String;)C',
  );

  static final _getChar =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallCharMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public char getChar(java.lang.String string)`
  core$_.int getChar(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getChar(
      reference.pointer,
      _id_getChar.pointer,
      _$string.pointer,
    ).char;
  }

  static final _id_getChar$1 = Bundle._class.instanceMethodId(
    r'getChar',
    r'(Ljava/lang/String;C)C',
  );

  static final _getChar$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallCharMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public char getChar(java.lang.String string, char c)`
  core$_.int getChar$1(jni$_.JString? string, core$_.int c) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getChar$1(
      reference.pointer,
      _id_getChar$1.pointer,
      _$string.pointer,
      c,
    ).char;
  }

  static final _id_getCharArray = Bundle._class.instanceMethodId(
    r'getCharArray',
    r'(Ljava/lang/String;)[C',
  );

  static final _getCharArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public char[] getCharArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JCharArray? getCharArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getCharArray(
      reference.pointer,
      _id_getCharArray.pointer,
      _$string.pointer,
    ).object<jni$_.JCharArray?>();
  }

  static final _id_getCharSequence = Bundle._class.instanceMethodId(
    r'getCharSequence',
    r'(Ljava/lang/String;)Ljava/lang/CharSequence;',
  );

  static final _getCharSequence =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.CharSequence getCharSequence(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getCharSequence(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getCharSequence(
      reference.pointer,
      _id_getCharSequence.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getCharSequence$1 = Bundle._class.instanceMethodId(
    r'getCharSequence',
    r'(Ljava/lang/String;Ljava/lang/CharSequence;)Ljava/lang/CharSequence;',
  );

  static final _getCharSequence$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.CharSequence getCharSequence(java.lang.String string, java.lang.CharSequence charSequence)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getCharSequence$1(
    jni$_.JString? string,
    jni$_.JObject? charSequence,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$charSequence = charSequence?.reference ?? jni$_.jNullReference;
    return _getCharSequence$1(
      reference.pointer,
      _id_getCharSequence$1.pointer,
      _$string.pointer,
      _$charSequence.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getCharSequenceArray = Bundle._class.instanceMethodId(
    r'getCharSequenceArray',
    r'(Ljava/lang/String;)[Ljava/lang/CharSequence;',
  );

  static final _getCharSequenceArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.CharSequence[] getCharSequenceArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<jni$_.JObject?>? getCharSequenceArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getCharSequenceArray(
      reference.pointer,
      _id_getCharSequenceArray.pointer,
      _$string.pointer,
    ).object<jni$_.JArray<jni$_.JObject?>?>();
  }

  static final _id_getCharSequenceArrayList = Bundle._class.instanceMethodId(
    r'getCharSequenceArrayList',
    r'(Ljava/lang/String;)Ljava/util/ArrayList;',
  );

  static final _getCharSequenceArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.ArrayList<java.lang.CharSequence> getCharSequenceArrayList(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getCharSequenceArrayList(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getCharSequenceArrayList(
      reference.pointer,
      _id_getCharSequenceArrayList.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$classLoader = Bundle._class.instanceMethodId(
    r'getClassLoader',
    r'()Ljava/lang/ClassLoader;',
  );

  static final _get$classLoader =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.ClassLoader getClassLoader()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get classLoader {
    return _get$classLoader(
      reference.pointer,
      _id_get$classLoader.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getFloat = Bundle._class.instanceMethodId(
    r'getFloat',
    r'(Ljava/lang/String;)F',
  );

  static final _getFloat =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallFloatMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public float getFloat(java.lang.String string)`
  core$_.double getFloat(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getFloat(
      reference.pointer,
      _id_getFloat.pointer,
      _$string.pointer,
    ).float;
  }

  static final _id_getFloat$1 = Bundle._class.instanceMethodId(
    r'getFloat',
    r'(Ljava/lang/String;F)F',
  );

  static final _getFloat$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Double)>,
              )
            >
          >('globalEnv_CallFloatMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
            )
          >();

  /// from: `public float getFloat(java.lang.String string, float f)`
  core$_.double getFloat$1(jni$_.JString? string, core$_.double f) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getFloat$1(
      reference.pointer,
      _id_getFloat$1.pointer,
      _$string.pointer,
      f,
    ).float;
  }

  static final _id_getFloatArray = Bundle._class.instanceMethodId(
    r'getFloatArray',
    r'(Ljava/lang/String;)[F',
  );

  static final _getFloatArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public float[] getFloatArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JFloatArray? getFloatArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getFloatArray(
      reference.pointer,
      _id_getFloatArray.pointer,
      _$string.pointer,
    ).object<jni$_.JFloatArray?>();
  }

  static final _id_getIntegerArrayList = Bundle._class.instanceMethodId(
    r'getIntegerArrayList',
    r'(Ljava/lang/String;)Ljava/util/ArrayList;',
  );

  static final _getIntegerArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.ArrayList<java.lang.Integer> getIntegerArrayList(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getIntegerArrayList(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getIntegerArrayList(
      reference.pointer,
      _id_getIntegerArrayList.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getParcelable = Bundle._class.instanceMethodId(
    r'getParcelable',
    r'(Ljava/lang/String;)Landroid/os/Parcelable;',
  );

  static final _getParcelable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T getParcelable(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getParcelable<$T extends jni$_.JObject?>(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getParcelable(
      reference.pointer,
      _id_getParcelable.pointer,
      _$string.pointer,
    ).object<$T?>();
  }

  static final _id_getParcelable$1 = Bundle._class.instanceMethodId(
    r'getParcelable',
    r'(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;',
  );

  static final _getParcelable$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T getParcelable(java.lang.String string, java.lang.Class<T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getParcelable$1<$T extends jni$_.JObject?>(
    jni$_.JString? string,
    jni$_.JObject? class$,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getParcelable$1(
      reference.pointer,
      _id_getParcelable$1.pointer,
      _$string.pointer,
      _$class$.pointer,
    ).object<$T?>();
  }

  static final _id_getParcelableArray = Bundle._class.instanceMethodId(
    r'getParcelableArray',
    r'(Ljava/lang/String;)[Landroid/os/Parcelable;',
  );

  static final _getParcelableArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.os.Parcelable[] getParcelableArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<jni$_.JObject?>? getParcelableArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getParcelableArray(
      reference.pointer,
      _id_getParcelableArray.pointer,
      _$string.pointer,
    ).object<jni$_.JArray<jni$_.JObject?>?>();
  }

  static final _id_getParcelableArray$1 = Bundle._class.instanceMethodId(
    r'getParcelableArray',
    r'(Ljava/lang/String;Ljava/lang/Class;)[Ljava/lang/Object;',
  );

  static final _getParcelableArray$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T[] getParcelableArray(java.lang.String string, java.lang.Class<T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<$T?>? getParcelableArray$1<$T extends jni$_.JObject?>(
    jni$_.JString? string,
    jni$_.JObject? class$,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getParcelableArray$1(
      reference.pointer,
      _id_getParcelableArray$1.pointer,
      _$string.pointer,
      _$class$.pointer,
    ).object<jni$_.JArray<$T?>?>();
  }

  static final _id_getParcelableArrayList = Bundle._class.instanceMethodId(
    r'getParcelableArrayList',
    r'(Ljava/lang/String;)Ljava/util/ArrayList;',
  );

  static final _getParcelableArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.ArrayList<T> getParcelableArrayList(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getParcelableArrayList<$T extends jni$_.JObject?>(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getParcelableArrayList(
      reference.pointer,
      _id_getParcelableArrayList.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getParcelableArrayList$1 = Bundle._class.instanceMethodId(
    r'getParcelableArrayList',
    r'(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/ArrayList;',
  );

  static final _getParcelableArrayList$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.ArrayList<T> getParcelableArrayList(java.lang.String string, java.lang.Class<? extends T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getParcelableArrayList$1<$T extends jni$_.JObject?>(
    jni$_.JString? string,
    jni$_.JObject? class$,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getParcelableArrayList$1(
      reference.pointer,
      _id_getParcelableArrayList$1.pointer,
      _$string.pointer,
      _$class$.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getSerializable = Bundle._class.instanceMethodId(
    r'getSerializable',
    r'(Ljava/lang/String;)Ljava/io/Serializable;',
  );

  static final _getSerializable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.io.Serializable getSerializable(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSerializable(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSerializable(
      reference.pointer,
      _id_getSerializable.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getSerializable$1 = Bundle._class.instanceMethodId(
    r'getSerializable',
    r'(Ljava/lang/String;Ljava/lang/Class;)Ljava/io/Serializable;',
  );

  static final _getSerializable$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public T getSerializable(java.lang.String string, java.lang.Class<T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getSerializable$1<$T extends jni$_.JObject?>(
    jni$_.JString? string,
    jni$_.JObject? class$,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getSerializable$1(
      reference.pointer,
      _id_getSerializable$1.pointer,
      _$string.pointer,
      _$class$.pointer,
    ).object<$T?>();
  }

  static final _id_getShort = Bundle._class.instanceMethodId(
    r'getShort',
    r'(Ljava/lang/String;)S',
  );

  static final _getShort =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallShortMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public short getShort(java.lang.String string)`
  core$_.int getShort(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getShort(
      reference.pointer,
      _id_getShort.pointer,
      _$string.pointer,
    ).short;
  }

  static final _id_getShort$1 = Bundle._class.instanceMethodId(
    r'getShort',
    r'(Ljava/lang/String;S)S',
  );

  static final _getShort$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallShortMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public short getShort(java.lang.String string, short s)`
  core$_.int getShort$1(jni$_.JString? string, core$_.int s) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getShort$1(
      reference.pointer,
      _id_getShort$1.pointer,
      _$string.pointer,
      s,
    ).short;
  }

  static final _id_getShortArray = Bundle._class.instanceMethodId(
    r'getShortArray',
    r'(Ljava/lang/String;)[S',
  );

  static final _getShortArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public short[] getShortArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JShortArray? getShortArray(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getShortArray(
      reference.pointer,
      _id_getShortArray.pointer,
      _$string.pointer,
    ).object<jni$_.JShortArray?>();
  }

  static final _id_getSize = Bundle._class.instanceMethodId(
    r'getSize',
    r'(Ljava/lang/String;)Landroid/util/Size;',
  );

  static final _getSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.util.Size getSize(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSize(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSize(
      reference.pointer,
      _id_getSize.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getSizeF = Bundle._class.instanceMethodId(
    r'getSizeF',
    r'(Ljava/lang/String;)Landroid/util/SizeF;',
  );

  static final _getSizeF =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.util.SizeF getSizeF(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSizeF(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSizeF(
      reference.pointer,
      _id_getSizeF.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getSparseParcelableArray = Bundle._class.instanceMethodId(
    r'getSparseParcelableArray',
    r'(Ljava/lang/String;)Landroid/util/SparseArray;',
  );

  static final _getSparseParcelableArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.util.SparseArray<T> getSparseParcelableArray(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSparseParcelableArray<$T extends jni$_.JObject?>(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSparseParcelableArray(
      reference.pointer,
      _id_getSparseParcelableArray.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getSparseParcelableArray$1 = Bundle._class.instanceMethodId(
    r'getSparseParcelableArray',
    r'(Ljava/lang/String;Ljava/lang/Class;)Landroid/util/SparseArray;',
  );

  static final _getSparseParcelableArray$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.util.SparseArray<T> getSparseParcelableArray(java.lang.String string, java.lang.Class<? extends T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSparseParcelableArray$1<$T extends jni$_.JObject?>(
    jni$_.JString? string,
    jni$_.JObject? class$,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getSparseParcelableArray$1(
      reference.pointer,
      _id_getSparseParcelableArray$1.pointer,
      _$string.pointer,
      _$class$.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_getStringArrayList = Bundle._class.instanceMethodId(
    r'getStringArrayList',
    r'(Ljava/lang/String;)Ljava/util/ArrayList;',
  );

  static final _getStringArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.ArrayList<java.lang.String> getStringArrayList(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getStringArrayList(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getStringArrayList(
      reference.pointer,
      _id_getStringArrayList.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_hasFileDescriptors = Bundle._class.instanceMethodId(
    r'hasFileDescriptors',
    r'()Z',
  );

  static final _hasFileDescriptors =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean hasFileDescriptors()`
  core$_.bool hasFileDescriptors() {
    return _hasFileDescriptors(
      reference.pointer,
      _id_hasFileDescriptors.pointer,
    ).boolean;
  }

  static final _id_putAll = Bundle._class.instanceMethodId(
    r'putAll',
    r'(Landroid/os/Bundle;)V',
  );

  static final _putAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putAll(android.os.Bundle bundle)`
  void putAll(Bundle? bundle) {
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _putAll(reference.pointer, _id_putAll.pointer, _$bundle.pointer).check();
  }

  static final _id_putBinder = Bundle._class.instanceMethodId(
    r'putBinder',
    r'(Ljava/lang/String;Landroid/os/IBinder;)V',
  );

  static final _putBinder =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putBinder(java.lang.String string, android.os.IBinder iBinder)`
  void putBinder(jni$_.JString? string, jni$_.JObject? iBinder) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$iBinder = iBinder?.reference ?? jni$_.jNullReference;
    _putBinder(
      reference.pointer,
      _id_putBinder.pointer,
      _$string.pointer,
      _$iBinder.pointer,
    ).check();
  }

  static final _id_putBundle = Bundle._class.instanceMethodId(
    r'putBundle',
    r'(Ljava/lang/String;Landroid/os/Bundle;)V',
  );

  static final _putBundle =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putBundle(java.lang.String string, android.os.Bundle bundle)`
  void putBundle(jni$_.JString? string, Bundle? bundle) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _putBundle(
      reference.pointer,
      _id_putBundle.pointer,
      _$string.pointer,
      _$bundle.pointer,
    ).check();
  }

  static final _id_putByte = Bundle._class.instanceMethodId(
    r'putByte',
    r'(Ljava/lang/String;B)V',
  );

  static final _putByte =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void putByte(java.lang.String string, byte b)`
  void putByte(jni$_.JString? string, core$_.int b) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _putByte(
      reference.pointer,
      _id_putByte.pointer,
      _$string.pointer,
      b,
    ).check();
  }

  static final _id_putByteArray = Bundle._class.instanceMethodId(
    r'putByteArray',
    r'(Ljava/lang/String;[B)V',
  );

  static final _putByteArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putByteArray(java.lang.String string, byte[] bs)`
  void putByteArray(jni$_.JString? string, jni$_.JByteArray? bs) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _putByteArray(
      reference.pointer,
      _id_putByteArray.pointer,
      _$string.pointer,
      _$bs.pointer,
    ).check();
  }

  static final _id_putChar = Bundle._class.instanceMethodId(
    r'putChar',
    r'(Ljava/lang/String;C)V',
  );

  static final _putChar =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void putChar(java.lang.String string, char c)`
  void putChar(jni$_.JString? string, core$_.int c) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _putChar(
      reference.pointer,
      _id_putChar.pointer,
      _$string.pointer,
      c,
    ).check();
  }

  static final _id_putCharArray = Bundle._class.instanceMethodId(
    r'putCharArray',
    r'(Ljava/lang/String;[C)V',
  );

  static final _putCharArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putCharArray(java.lang.String string, char[] cs)`
  void putCharArray(jni$_.JString? string, jni$_.JCharArray? cs) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$cs = cs?.reference ?? jni$_.jNullReference;
    _putCharArray(
      reference.pointer,
      _id_putCharArray.pointer,
      _$string.pointer,
      _$cs.pointer,
    ).check();
  }

  static final _id_putCharSequence = Bundle._class.instanceMethodId(
    r'putCharSequence',
    r'(Ljava/lang/String;Ljava/lang/CharSequence;)V',
  );

  static final _putCharSequence =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putCharSequence(java.lang.String string, java.lang.CharSequence charSequence)`
  void putCharSequence(jni$_.JString? string, jni$_.JObject? charSequence) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$charSequence = charSequence?.reference ?? jni$_.jNullReference;
    _putCharSequence(
      reference.pointer,
      _id_putCharSequence.pointer,
      _$string.pointer,
      _$charSequence.pointer,
    ).check();
  }

  static final _id_putCharSequenceArray = Bundle._class.instanceMethodId(
    r'putCharSequenceArray',
    r'(Ljava/lang/String;[Ljava/lang/CharSequence;)V',
  );

  static final _putCharSequenceArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putCharSequenceArray(java.lang.String string, java.lang.CharSequence[] charSequences)`
  void putCharSequenceArray(
    jni$_.JString? string,
    jni$_.JArray<jni$_.JObject?>? charSequences,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$charSequences = charSequences?.reference ?? jni$_.jNullReference;
    _putCharSequenceArray(
      reference.pointer,
      _id_putCharSequenceArray.pointer,
      _$string.pointer,
      _$charSequences.pointer,
    ).check();
  }

  static final _id_putCharSequenceArrayList = Bundle._class.instanceMethodId(
    r'putCharSequenceArrayList',
    r'(Ljava/lang/String;Ljava/util/ArrayList;)V',
  );

  static final _putCharSequenceArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putCharSequenceArrayList(java.lang.String string, java.util.ArrayList<java.lang.CharSequence> arrayList)`
  void putCharSequenceArrayList(
    jni$_.JString? string,
    jni$_.JObject? arrayList,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$arrayList = arrayList?.reference ?? jni$_.jNullReference;
    _putCharSequenceArrayList(
      reference.pointer,
      _id_putCharSequenceArrayList.pointer,
      _$string.pointer,
      _$arrayList.pointer,
    ).check();
  }

  static final _id_putFloat = Bundle._class.instanceMethodId(
    r'putFloat',
    r'(Ljava/lang/String;F)V',
  );

  static final _putFloat =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Double)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
            )
          >();

  /// from: `public void putFloat(java.lang.String string, float f)`
  void putFloat(jni$_.JString? string, core$_.double f) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _putFloat(
      reference.pointer,
      _id_putFloat.pointer,
      _$string.pointer,
      f,
    ).check();
  }

  static final _id_putFloatArray = Bundle._class.instanceMethodId(
    r'putFloatArray',
    r'(Ljava/lang/String;[F)V',
  );

  static final _putFloatArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putFloatArray(java.lang.String string, float[] fs)`
  void putFloatArray(jni$_.JString? string, jni$_.JFloatArray? fs) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$fs = fs?.reference ?? jni$_.jNullReference;
    _putFloatArray(
      reference.pointer,
      _id_putFloatArray.pointer,
      _$string.pointer,
      _$fs.pointer,
    ).check();
  }

  static final _id_putIntegerArrayList = Bundle._class.instanceMethodId(
    r'putIntegerArrayList',
    r'(Ljava/lang/String;Ljava/util/ArrayList;)V',
  );

  static final _putIntegerArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putIntegerArrayList(java.lang.String string, java.util.ArrayList<java.lang.Integer> arrayList)`
  void putIntegerArrayList(jni$_.JString? string, jni$_.JObject? arrayList) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$arrayList = arrayList?.reference ?? jni$_.jNullReference;
    _putIntegerArrayList(
      reference.pointer,
      _id_putIntegerArrayList.pointer,
      _$string.pointer,
      _$arrayList.pointer,
    ).check();
  }

  static final _id_putParcelable = Bundle._class.instanceMethodId(
    r'putParcelable',
    r'(Ljava/lang/String;Landroid/os/Parcelable;)V',
  );

  static final _putParcelable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putParcelable(java.lang.String string, android.os.Parcelable parcelable)`
  void putParcelable(jni$_.JString? string, jni$_.JObject? parcelable) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$parcelable = parcelable?.reference ?? jni$_.jNullReference;
    _putParcelable(
      reference.pointer,
      _id_putParcelable.pointer,
      _$string.pointer,
      _$parcelable.pointer,
    ).check();
  }

  static final _id_putParcelableArray = Bundle._class.instanceMethodId(
    r'putParcelableArray',
    r'(Ljava/lang/String;[Landroid/os/Parcelable;)V',
  );

  static final _putParcelableArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putParcelableArray(java.lang.String string, android.os.Parcelable[] parcelables)`
  void putParcelableArray(
    jni$_.JString? string,
    jni$_.JArray<jni$_.JObject?>? parcelables,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$parcelables = parcelables?.reference ?? jni$_.jNullReference;
    _putParcelableArray(
      reference.pointer,
      _id_putParcelableArray.pointer,
      _$string.pointer,
      _$parcelables.pointer,
    ).check();
  }

  static final _id_putParcelableArrayList = Bundle._class.instanceMethodId(
    r'putParcelableArrayList',
    r'(Ljava/lang/String;Ljava/util/ArrayList;)V',
  );

  static final _putParcelableArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putParcelableArrayList(java.lang.String string, java.util.ArrayList<? extends android.os.Parcelable> arrayList)`
  void putParcelableArrayList(jni$_.JString? string, jni$_.JObject? arrayList) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$arrayList = arrayList?.reference ?? jni$_.jNullReference;
    _putParcelableArrayList(
      reference.pointer,
      _id_putParcelableArrayList.pointer,
      _$string.pointer,
      _$arrayList.pointer,
    ).check();
  }

  static final _id_putSerializable = Bundle._class.instanceMethodId(
    r'putSerializable',
    r'(Ljava/lang/String;Ljava/io/Serializable;)V',
  );

  static final _putSerializable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putSerializable(java.lang.String string, java.io.Serializable serializable)`
  void putSerializable(jni$_.JString? string, jni$_.JObject? serializable) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$serializable = serializable?.reference ?? jni$_.jNullReference;
    _putSerializable(
      reference.pointer,
      _id_putSerializable.pointer,
      _$string.pointer,
      _$serializable.pointer,
    ).check();
  }

  static final _id_putShort = Bundle._class.instanceMethodId(
    r'putShort',
    r'(Ljava/lang/String;S)V',
  );

  static final _putShort =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void putShort(java.lang.String string, short s)`
  void putShort(jni$_.JString? string, core$_.int s) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _putShort(
      reference.pointer,
      _id_putShort.pointer,
      _$string.pointer,
      s,
    ).check();
  }

  static final _id_putShortArray = Bundle._class.instanceMethodId(
    r'putShortArray',
    r'(Ljava/lang/String;[S)V',
  );

  static final _putShortArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putShortArray(java.lang.String string, short[] ss)`
  void putShortArray(jni$_.JString? string, jni$_.JShortArray? ss) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$ss = ss?.reference ?? jni$_.jNullReference;
    _putShortArray(
      reference.pointer,
      _id_putShortArray.pointer,
      _$string.pointer,
      _$ss.pointer,
    ).check();
  }

  static final _id_putSize = Bundle._class.instanceMethodId(
    r'putSize',
    r'(Ljava/lang/String;Landroid/util/Size;)V',
  );

  static final _putSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putSize(java.lang.String string, android.util.Size size)`
  void putSize(jni$_.JString? string, jni$_.JObject? size) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$size = size?.reference ?? jni$_.jNullReference;
    _putSize(
      reference.pointer,
      _id_putSize.pointer,
      _$string.pointer,
      _$size.pointer,
    ).check();
  }

  static final _id_putSizeF = Bundle._class.instanceMethodId(
    r'putSizeF',
    r'(Ljava/lang/String;Landroid/util/SizeF;)V',
  );

  static final _putSizeF =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putSizeF(java.lang.String string, android.util.SizeF sizeF)`
  void putSizeF(jni$_.JString? string, jni$_.JObject? sizeF) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$sizeF = sizeF?.reference ?? jni$_.jNullReference;
    _putSizeF(
      reference.pointer,
      _id_putSizeF.pointer,
      _$string.pointer,
      _$sizeF.pointer,
    ).check();
  }

  static final _id_putSparseParcelableArray = Bundle._class.instanceMethodId(
    r'putSparseParcelableArray',
    r'(Ljava/lang/String;Landroid/util/SparseArray;)V',
  );

  static final _putSparseParcelableArray =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putSparseParcelableArray(java.lang.String string, android.util.SparseArray<? extends android.os.Parcelable> sparseArray)`
  void putSparseParcelableArray(
    jni$_.JString? string,
    jni$_.JObject? sparseArray,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$sparseArray = sparseArray?.reference ?? jni$_.jNullReference;
    _putSparseParcelableArray(
      reference.pointer,
      _id_putSparseParcelableArray.pointer,
      _$string.pointer,
      _$sparseArray.pointer,
    ).check();
  }

  static final _id_putStringArrayList = Bundle._class.instanceMethodId(
    r'putStringArrayList',
    r'(Ljava/lang/String;Ljava/util/ArrayList;)V',
  );

  static final _putStringArrayList =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putStringArrayList(java.lang.String string, java.util.ArrayList<java.lang.String> arrayList)`
  void putStringArrayList(jni$_.JString? string, jni$_.JObject? arrayList) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$arrayList = arrayList?.reference ?? jni$_.jNullReference;
    _putStringArrayList(
      reference.pointer,
      _id_putStringArrayList.pointer,
      _$string.pointer,
      _$arrayList.pointer,
    ).check();
  }

  static final _id_readFromParcel = Bundle._class.instanceMethodId(
    r'readFromParcel',
    r'(Landroid/os/Parcel;)V',
  );

  static final _readFromParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void readFromParcel(android.os.Parcel parcel)`
  void readFromParcel(jni$_.JObject? parcel) {
    final _$parcel = parcel?.reference ?? jni$_.jNullReference;
    _readFromParcel(
      reference.pointer,
      _id_readFromParcel.pointer,
      _$parcel.pointer,
    ).check();
  }

  static final _id_remove = Bundle._class.instanceMethodId(
    r'remove',
    r'(Ljava/lang/String;)V',
  );

  static final _remove =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void remove(java.lang.String string)`
  void remove(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _remove(reference.pointer, _id_remove.pointer, _$string.pointer).check();
  }

  static final _id_set$classLoader = Bundle._class.instanceMethodId(
    r'setClassLoader',
    r'(Ljava/lang/ClassLoader;)V',
  );

  static final _set$classLoader =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void setClassLoader(java.lang.ClassLoader classLoader)`
  set classLoader(jni$_.JObject? classLoader) {
    final _$classLoader = classLoader?.reference ?? jni$_.jNullReference;
    _set$classLoader(
      reference.pointer,
      _id_set$classLoader.pointer,
      _$classLoader.pointer,
    ).check();
  }

  static final _id_toString$1 = Bundle._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_writeToParcel = Bundle._class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(jni$_.JObject? parcel, core$_.int i) {
    final _$parcel = parcel?.reference ?? jni$_.jNullReference;
    _writeToParcel(
      reference.pointer,
      _id_writeToParcel.pointer,
      _$parcel.pointer,
      i,
    ).check();
  }
}

final class $Bundle$Type$ extends jni$_.JType<Bundle> {
  @jni$_.internal
  const $Bundle$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Bundle;';
}
