// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'File.dart' as file$_;

/// from: `java.io.FileOutputStream`
extension type FileOutputStream._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'java/io/FileOutputStream');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FileOutputStream> type = $FileOutputStream$Type$();
  static final _id_new$ = _class.constructorId(r'(Ljava/io/File;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.io.File file)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileOutputStream(file$_.File? file) {
    final _$file = file?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$file.pointer,
    ).object<FileOutputStream>();
  }

  static final _id_new$1 = _class.constructorId(r'(Ljava/io/File;Z)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.io.File file, boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileOutputStream.new$1(file$_.File? file, core$_.bool z) {
    final _$file = file?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$file.pointer,
      z ? 1 : 0,
    ).object<FileOutputStream>();
  }

  static final _id_new$2 = _class.constructorId(r'(Ljava/io/FileDescriptor;)V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.io.FileDescriptor fileDescriptor)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileOutputStream.new$2(jni$_.JObject? fileDescriptor) {
    final _$fileDescriptor = fileDescriptor?.reference ?? jni$_.jNullReference;
    return _new$2(
      _class.reference.pointer,
      _id_new$2.pointer,
      _$fileDescriptor.pointer,
    ).object<FileOutputStream>();
  }

  static final _id_new$3 = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileOutputStream.new$3(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _new$3(
      _class.reference.pointer,
      _id_new$3.pointer,
      _$string.pointer,
    ).object<FileOutputStream>();
  }

  static final _id_new$4 = _class.constructorId(r'(Ljava/lang/String;Z)V');

  static final _new$4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  factory FileOutputStream.new$4(jni$_.JString? string, core$_.bool z) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _new$4(
      _class.reference.pointer,
      _id_new$4.pointer,
      _$string.pointer,
      z ? 1 : 0,
    ).object<FileOutputStream>();
  }
}

extension FileOutputStream$$Methods on FileOutputStream {
  static final _id_close = FileOutputStream._class.instanceMethodId(
    r'close',
    r'()V',
  );

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void close()`
  void close() {
    _close(reference.pointer, _id_close.pointer).check();
  }

  static final _id_get$channel = FileOutputStream._class.instanceMethodId(
    r'getChannel',
    r'()Ljava/nio/channels/FileChannel;',
  );

  static final _get$channel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.nio.channels.FileChannel getChannel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get channel {
    return _get$channel(
      reference.pointer,
      _id_get$channel.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_get$fD = FileOutputStream._class.instanceMethodId(
    r'getFD',
    r'()Ljava/io/FileDescriptor;',
  );

  static final _get$fD =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.io.FileDescriptor getFD()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get fD {
    return _get$fD(
      reference.pointer,
      _id_get$fD.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_write = FileOutputStream._class.instanceMethodId(
    r'write',
    r'([B)V',
  );

  static final _write =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void write(byte[] bs)`
  void write(jni$_.JByteArray? bs) {
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _write(reference.pointer, _id_write.pointer, _$bs.pointer).check();
  }

  static final _id_write$1 = FileOutputStream._class.instanceMethodId(
    r'write',
    r'([BII)V',
  );

  static final _write$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void write(byte[] bs, int i, int i1)`
  void write$1(jni$_.JByteArray? bs, core$_.int i, core$_.int i1) {
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _write$1(
      reference.pointer,
      _id_write$1.pointer,
      _$bs.pointer,
      i,
      i1,
    ).check();
  }

  static final _id_write$2 = FileOutputStream._class.instanceMethodId(
    r'write',
    r'(I)V',
  );

  static final _write$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void write(int i)`
  void write$2(core$_.int i) {
    _write$2(reference.pointer, _id_write$2.pointer, i).check();
  }
}

final class $FileOutputStream$Type$ extends jni$_.JType<FileOutputStream> {
  @jni$_.internal
  const $FileOutputStream$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/io/FileOutputStream;';
}
