// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'WebResourceError.dart' as webresourceerror$_;

import 'WebResourceRequest.dart' as webresourcerequest$_;

import 'WebView.dart' as webview$_;

/// from: `android.webkit.WebViewClient`
extension type WebViewClient._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/webkit/WebViewClient');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WebViewClient> type = $WebViewClient$Type$();

  /// from: `static public final int ERROR_AUTHENTICATION`
  static const ERROR_AUTHENTICATION = -4;

  /// from: `static public final int ERROR_BAD_URL`
  static const ERROR_BAD_URL = -12;

  /// from: `static public final int ERROR_CONNECT`
  static const ERROR_CONNECT = -6;

  /// from: `static public final int ERROR_FAILED_SSL_HANDSHAKE`
  static const ERROR_FAILED_SSL_HANDSHAKE = -11;

  /// from: `static public final int ERROR_FILE`
  static const ERROR_FILE = -13;

  /// from: `static public final int ERROR_FILE_NOT_FOUND`
  static const ERROR_FILE_NOT_FOUND = -14;

  /// from: `static public final int ERROR_HOST_LOOKUP`
  static const ERROR_HOST_LOOKUP = -2;

  /// from: `static public final int ERROR_IO`
  static const ERROR_IO = -7;

  /// from: `static public final int ERROR_PROXY_AUTHENTICATION`
  static const ERROR_PROXY_AUTHENTICATION = -5;

  /// from: `static public final int ERROR_REDIRECT_LOOP`
  static const ERROR_REDIRECT_LOOP = -9;

  /// from: `static public final int ERROR_TIMEOUT`
  static const ERROR_TIMEOUT = -8;

  /// from: `static public final int ERROR_TOO_MANY_REQUESTS`
  static const ERROR_TOO_MANY_REQUESTS = -15;

  /// from: `static public final int ERROR_UNKNOWN`
  static const ERROR_UNKNOWN = -1;

  /// from: `static public final int ERROR_UNSAFE_RESOURCE`
  static const ERROR_UNSAFE_RESOURCE = -16;

  /// from: `static public final int ERROR_UNSUPPORTED_AUTH_SCHEME`
  static const ERROR_UNSUPPORTED_AUTH_SCHEME = -3;

  /// from: `static public final int ERROR_UNSUPPORTED_SCHEME`
  static const ERROR_UNSUPPORTED_SCHEME = -10;

  /// from: `static public final int SAFE_BROWSING_THREAT_BILLING`
  static const SAFE_BROWSING_THREAT_BILLING = 4;

  /// from: `static public final int SAFE_BROWSING_THREAT_MALWARE`
  static const SAFE_BROWSING_THREAT_MALWARE = 1;

  /// from: `static public final int SAFE_BROWSING_THREAT_PHISHING`
  static const SAFE_BROWSING_THREAT_PHISHING = 2;

  /// from: `static public final int SAFE_BROWSING_THREAT_UNKNOWN`
  static const SAFE_BROWSING_THREAT_UNKNOWN = 0;

  /// from: `static public final int SAFE_BROWSING_THREAT_UNWANTED_SOFTWARE`
  static const SAFE_BROWSING_THREAT_UNWANTED_SOFTWARE = 3;
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory WebViewClient() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<WebViewClient>();
  }
}

extension WebViewClient$$Methods on WebViewClient {
  static final _id_doUpdateVisitedHistory = WebViewClient._class
      .instanceMethodId(
        r'doUpdateVisitedHistory',
        r'(Landroid/webkit/WebView;Ljava/lang/String;Z)V',
      );

  static final _doUpdateVisitedHistory =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void doUpdateVisitedHistory(android.webkit.WebView webView, java.lang.String string, boolean z)`
  void doUpdateVisitedHistory(
    webview$_.WebView? webView,
    jni$_.JString? string,
    core$_.bool z,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    _doUpdateVisitedHistory(
      reference.pointer,
      _id_doUpdateVisitedHistory.pointer,
      _$webView.pointer,
      _$string.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_onFormResubmission = WebViewClient._class.instanceMethodId(
    r'onFormResubmission',
    r'(Landroid/webkit/WebView;Landroid/os/Message;Landroid/os/Message;)V',
  );

  static final _onFormResubmission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onFormResubmission(android.webkit.WebView webView, android.os.Message message, android.os.Message message1)`
  void onFormResubmission(
    webview$_.WebView? webView,
    jni$_.JObject? message,
    jni$_.JObject? message1,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$message = message?.reference ?? jni$_.jNullReference;
    final _$message1 = message1?.reference ?? jni$_.jNullReference;
    _onFormResubmission(
      reference.pointer,
      _id_onFormResubmission.pointer,
      _$webView.pointer,
      _$message.pointer,
      _$message1.pointer,
    ).check();
  }

  static final _id_onLoadResource = WebViewClient._class.instanceMethodId(
    r'onLoadResource',
    r'(Landroid/webkit/WebView;Ljava/lang/String;)V',
  );

  static final _onLoadResource =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onLoadResource(android.webkit.WebView webView, java.lang.String string)`
  void onLoadResource(webview$_.WebView? webView, jni$_.JString? string) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    _onLoadResource(
      reference.pointer,
      _id_onLoadResource.pointer,
      _$webView.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_onPageCommitVisible = WebViewClient._class.instanceMethodId(
    r'onPageCommitVisible',
    r'(Landroid/webkit/WebView;Ljava/lang/String;)V',
  );

  static final _onPageCommitVisible =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onPageCommitVisible(android.webkit.WebView webView, java.lang.String string)`
  void onPageCommitVisible(webview$_.WebView? webView, jni$_.JString? string) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    _onPageCommitVisible(
      reference.pointer,
      _id_onPageCommitVisible.pointer,
      _$webView.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_onPageFinished = WebViewClient._class.instanceMethodId(
    r'onPageFinished',
    r'(Landroid/webkit/WebView;Ljava/lang/String;)V',
  );

  static final _onPageFinished =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onPageFinished(android.webkit.WebView webView, java.lang.String string)`
  void onPageFinished(webview$_.WebView? webView, jni$_.JString? string) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    _onPageFinished(
      reference.pointer,
      _id_onPageFinished.pointer,
      _$webView.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_onPageStarted = WebViewClient._class.instanceMethodId(
    r'onPageStarted',
    r'(Landroid/webkit/WebView;Ljava/lang/String;Landroid/graphics/Bitmap;)V',
  );

  static final _onPageStarted =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onPageStarted(android.webkit.WebView webView, java.lang.String string, android.graphics.Bitmap bitmap)`
  void onPageStarted(
    webview$_.WebView? webView,
    jni$_.JString? string,
    jni$_.JObject? bitmap,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$bitmap = bitmap?.reference ?? jni$_.jNullReference;
    _onPageStarted(
      reference.pointer,
      _id_onPageStarted.pointer,
      _$webView.pointer,
      _$string.pointer,
      _$bitmap.pointer,
    ).check();
  }

  static final _id_onReceivedClientCertRequest = WebViewClient._class
      .instanceMethodId(
        r'onReceivedClientCertRequest',
        r'(Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V',
      );

  static final _onReceivedClientCertRequest =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedClientCertRequest(android.webkit.WebView webView, android.webkit.ClientCertRequest clientCertRequest)`
  void onReceivedClientCertRequest(
    webview$_.WebView? webView,
    jni$_.JObject? clientCertRequest,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$clientCertRequest =
        clientCertRequest?.reference ?? jni$_.jNullReference;
    _onReceivedClientCertRequest(
      reference.pointer,
      _id_onReceivedClientCertRequest.pointer,
      _$webView.pointer,
      _$clientCertRequest.pointer,
    ).check();
  }

  static final _id_onReceivedError = WebViewClient._class.instanceMethodId(
    r'onReceivedError',
    r'(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;Landroid/webkit/WebResourceError;)V',
  );

  static final _onReceivedError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedError(android.webkit.WebView webView, android.webkit.WebResourceRequest webResourceRequest, android.webkit.WebResourceError webResourceError)`
  void onReceivedError(
    webview$_.WebView? webView,
    webresourcerequest$_.WebResourceRequest? webResourceRequest,
    webresourceerror$_.WebResourceError? webResourceError,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$webResourceRequest =
        webResourceRequest?.reference ?? jni$_.jNullReference;
    final _$webResourceError =
        webResourceError?.reference ?? jni$_.jNullReference;
    _onReceivedError(
      reference.pointer,
      _id_onReceivedError.pointer,
      _$webView.pointer,
      _$webResourceRequest.pointer,
      _$webResourceError.pointer,
    ).check();
  }

  static final _id_onReceivedError$1 = WebViewClient._class.instanceMethodId(
    r'onReceivedError',
    r'(Landroid/webkit/WebView;ILjava/lang/String;Ljava/lang/String;)V',
  );

  static final _onReceivedError$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedError(android.webkit.WebView webView, int i, java.lang.String string, java.lang.String string1)`
  void onReceivedError$1(
    webview$_.WebView? webView,
    core$_.int i,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _onReceivedError$1(
      reference.pointer,
      _id_onReceivedError$1.pointer,
      _$webView.pointer,
      i,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_onReceivedHttpAuthRequest = WebViewClient._class
      .instanceMethodId(
        r'onReceivedHttpAuthRequest',
        r'(Landroid/webkit/WebView;Landroid/webkit/HttpAuthHandler;Ljava/lang/String;Ljava/lang/String;)V',
      );

  static final _onReceivedHttpAuthRequest =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedHttpAuthRequest(android.webkit.WebView webView, android.webkit.HttpAuthHandler httpAuthHandler, java.lang.String string, java.lang.String string1)`
  void onReceivedHttpAuthRequest(
    webview$_.WebView? webView,
    jni$_.JObject? httpAuthHandler,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$httpAuthHandler =
        httpAuthHandler?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _onReceivedHttpAuthRequest(
      reference.pointer,
      _id_onReceivedHttpAuthRequest.pointer,
      _$webView.pointer,
      _$httpAuthHandler.pointer,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_onReceivedHttpError = WebViewClient._class.instanceMethodId(
    r'onReceivedHttpError',
    r'(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;Landroid/webkit/WebResourceResponse;)V',
  );

  static final _onReceivedHttpError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedHttpError(android.webkit.WebView webView, android.webkit.WebResourceRequest webResourceRequest, android.webkit.WebResourceResponse webResourceResponse)`
  void onReceivedHttpError(
    webview$_.WebView? webView,
    webresourcerequest$_.WebResourceRequest? webResourceRequest,
    jni$_.JObject? webResourceResponse,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$webResourceRequest =
        webResourceRequest?.reference ?? jni$_.jNullReference;
    final _$webResourceResponse =
        webResourceResponse?.reference ?? jni$_.jNullReference;
    _onReceivedHttpError(
      reference.pointer,
      _id_onReceivedHttpError.pointer,
      _$webView.pointer,
      _$webResourceRequest.pointer,
      _$webResourceResponse.pointer,
    ).check();
  }

  static final _id_onReceivedLoginRequest = WebViewClient._class.instanceMethodId(
    r'onReceivedLoginRequest',
    r'(Landroid/webkit/WebView;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _onReceivedLoginRequest =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedLoginRequest(android.webkit.WebView webView, java.lang.String string, java.lang.String string1, java.lang.String string2)`
  void onReceivedLoginRequest(
    webview$_.WebView? webView,
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    _onReceivedLoginRequest(
      reference.pointer,
      _id_onReceivedLoginRequest.pointer,
      _$webView.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).check();
  }

  static final _id_onReceivedSslError = WebViewClient._class.instanceMethodId(
    r'onReceivedSslError',
    r'(Landroid/webkit/WebView;Landroid/webkit/SslErrorHandler;Landroid/net/http/SslError;)V',
  );

  static final _onReceivedSslError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onReceivedSslError(android.webkit.WebView webView, android.webkit.SslErrorHandler sslErrorHandler, android.net.http.SslError sslError)`
  void onReceivedSslError(
    webview$_.WebView? webView,
    jni$_.JObject? sslErrorHandler,
    jni$_.JObject? sslError,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$sslErrorHandler =
        sslErrorHandler?.reference ?? jni$_.jNullReference;
    final _$sslError = sslError?.reference ?? jni$_.jNullReference;
    _onReceivedSslError(
      reference.pointer,
      _id_onReceivedSslError.pointer,
      _$webView.pointer,
      _$sslErrorHandler.pointer,
      _$sslError.pointer,
    ).check();
  }

  static final _id_onRenderProcessGone = WebViewClient._class.instanceMethodId(
    r'onRenderProcessGone',
    r'(Landroid/webkit/WebView;Landroid/webkit/RenderProcessGoneDetail;)Z',
  );

  static final _onRenderProcessGone =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean onRenderProcessGone(android.webkit.WebView webView, android.webkit.RenderProcessGoneDetail renderProcessGoneDetail)`
  core$_.bool onRenderProcessGone(
    webview$_.WebView? webView,
    jni$_.JObject? renderProcessGoneDetail,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$renderProcessGoneDetail =
        renderProcessGoneDetail?.reference ?? jni$_.jNullReference;
    return _onRenderProcessGone(
      reference.pointer,
      _id_onRenderProcessGone.pointer,
      _$webView.pointer,
      _$renderProcessGoneDetail.pointer,
    ).boolean;
  }

  static final _id_onSafeBrowsingHit = WebViewClient._class.instanceMethodId(
    r'onSafeBrowsingHit',
    r'(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;ILandroid/webkit/SafeBrowsingResponse;)V',
  );

  static final _onSafeBrowsingHit =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onSafeBrowsingHit(android.webkit.WebView webView, android.webkit.WebResourceRequest webResourceRequest, int i, android.webkit.SafeBrowsingResponse safeBrowsingResponse)`
  void onSafeBrowsingHit(
    webview$_.WebView? webView,
    webresourcerequest$_.WebResourceRequest? webResourceRequest,
    core$_.int i,
    jni$_.JObject? safeBrowsingResponse,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$webResourceRequest =
        webResourceRequest?.reference ?? jni$_.jNullReference;
    final _$safeBrowsingResponse =
        safeBrowsingResponse?.reference ?? jni$_.jNullReference;
    _onSafeBrowsingHit(
      reference.pointer,
      _id_onSafeBrowsingHit.pointer,
      _$webView.pointer,
      _$webResourceRequest.pointer,
      i,
      _$safeBrowsingResponse.pointer,
    ).check();
  }

  static final _id_onScaleChanged = WebViewClient._class.instanceMethodId(
    r'onScaleChanged',
    r'(Landroid/webkit/WebView;FF)V',
  );

  static final _onScaleChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Double, jni$_.Double)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
              core$_.double,
            )
          >();

  /// from: `public void onScaleChanged(android.webkit.WebView webView, float f, float f1)`
  void onScaleChanged(
    webview$_.WebView? webView,
    core$_.double f,
    core$_.double f1,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    _onScaleChanged(
      reference.pointer,
      _id_onScaleChanged.pointer,
      _$webView.pointer,
      f,
      f1,
    ).check();
  }

  static final _id_onTooManyRedirects = WebViewClient._class.instanceMethodId(
    r'onTooManyRedirects',
    r'(Landroid/webkit/WebView;Landroid/os/Message;Landroid/os/Message;)V',
  );

  static final _onTooManyRedirects =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onTooManyRedirects(android.webkit.WebView webView, android.os.Message message, android.os.Message message1)`
  void onTooManyRedirects(
    webview$_.WebView? webView,
    jni$_.JObject? message,
    jni$_.JObject? message1,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$message = message?.reference ?? jni$_.jNullReference;
    final _$message1 = message1?.reference ?? jni$_.jNullReference;
    _onTooManyRedirects(
      reference.pointer,
      _id_onTooManyRedirects.pointer,
      _$webView.pointer,
      _$message.pointer,
      _$message1.pointer,
    ).check();
  }

  static final _id_onUnhandledKeyEvent = WebViewClient._class.instanceMethodId(
    r'onUnhandledKeyEvent',
    r'(Landroid/webkit/WebView;Landroid/view/KeyEvent;)V',
  );

  static final _onUnhandledKeyEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onUnhandledKeyEvent(android.webkit.WebView webView, android.view.KeyEvent keyEvent)`
  void onUnhandledKeyEvent(
    webview$_.WebView? webView,
    jni$_.JObject? keyEvent,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$keyEvent = keyEvent?.reference ?? jni$_.jNullReference;
    _onUnhandledKeyEvent(
      reference.pointer,
      _id_onUnhandledKeyEvent.pointer,
      _$webView.pointer,
      _$keyEvent.pointer,
    ).check();
  }

  static final _id_shouldInterceptRequest = WebViewClient._class.instanceMethodId(
    r'shouldInterceptRequest',
    r'(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Landroid/webkit/WebResourceResponse;',
  );

  static final _shouldInterceptRequest =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView webView, android.webkit.WebResourceRequest webResourceRequest)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? shouldInterceptRequest(
    webview$_.WebView? webView,
    webresourcerequest$_.WebResourceRequest? webResourceRequest,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$webResourceRequest =
        webResourceRequest?.reference ?? jni$_.jNullReference;
    return _shouldInterceptRequest(
      reference.pointer,
      _id_shouldInterceptRequest.pointer,
      _$webView.pointer,
      _$webResourceRequest.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_shouldInterceptRequest$1 = WebViewClient._class.instanceMethodId(
    r'shouldInterceptRequest',
    r'(Landroid/webkit/WebView;Ljava/lang/String;)Landroid/webkit/WebResourceResponse;',
  );

  static final _shouldInterceptRequest$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView webView, java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? shouldInterceptRequest$1(
    webview$_.WebView? webView,
    jni$_.JString? string,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _shouldInterceptRequest$1(
      reference.pointer,
      _id_shouldInterceptRequest$1.pointer,
      _$webView.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_shouldOverrideKeyEvent = WebViewClient._class
      .instanceMethodId(
        r'shouldOverrideKeyEvent',
        r'(Landroid/webkit/WebView;Landroid/view/KeyEvent;)Z',
      );

  static final _shouldOverrideKeyEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean shouldOverrideKeyEvent(android.webkit.WebView webView, android.view.KeyEvent keyEvent)`
  core$_.bool shouldOverrideKeyEvent(
    webview$_.WebView? webView,
    jni$_.JObject? keyEvent,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$keyEvent = keyEvent?.reference ?? jni$_.jNullReference;
    return _shouldOverrideKeyEvent(
      reference.pointer,
      _id_shouldOverrideKeyEvent.pointer,
      _$webView.pointer,
      _$keyEvent.pointer,
    ).boolean;
  }

  static final _id_shouldOverrideUrlLoading = WebViewClient._class
      .instanceMethodId(
        r'shouldOverrideUrlLoading',
        r'(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Z',
      );

  static final _shouldOverrideUrlLoading =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean shouldOverrideUrlLoading(android.webkit.WebView webView, android.webkit.WebResourceRequest webResourceRequest)`
  core$_.bool shouldOverrideUrlLoading(
    webview$_.WebView? webView,
    webresourcerequest$_.WebResourceRequest? webResourceRequest,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$webResourceRequest =
        webResourceRequest?.reference ?? jni$_.jNullReference;
    return _shouldOverrideUrlLoading(
      reference.pointer,
      _id_shouldOverrideUrlLoading.pointer,
      _$webView.pointer,
      _$webResourceRequest.pointer,
    ).boolean;
  }

  static final _id_shouldOverrideUrlLoading$1 = WebViewClient._class
      .instanceMethodId(
        r'shouldOverrideUrlLoading',
        r'(Landroid/webkit/WebView;Ljava/lang/String;)Z',
      );

  static final _shouldOverrideUrlLoading$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean shouldOverrideUrlLoading(android.webkit.WebView webView, java.lang.String string)`
  core$_.bool shouldOverrideUrlLoading$1(
    webview$_.WebView? webView,
    jni$_.JString? string,
  ) {
    final _$webView = webView?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _shouldOverrideUrlLoading$1(
      reference.pointer,
      _id_shouldOverrideUrlLoading$1.pointer,
      _$webView.pointer,
      _$string.pointer,
    ).boolean;
  }
}

final class $WebViewClient$Type$ extends jni$_.JType<WebViewClient> {
  @jni$_.internal
  const $WebViewClient$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/webkit/WebViewClient;';
}
