#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint native_video_toolkit.podspec` to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'native_video_toolkit'
  s.version          = '0.0.1'
  s.summary          = 'AVFoundation-backed compress/merge/mute/reverse video toolkit.'
  s.description      = <<-DESC
Direct AVFoundation bindings (compress/merge/mute/reverse) generated by
ffigen's Objective-C interop + package:objective_c — no hand-written native
code, no Dart MethodChannel. The Swift plugin class only exists to satisfy
Flutter's plugin registration. Shares its generated bindings with the macOS
target (see macos/native_video_toolkit.podspec) — the AVFoundation surface
this package binds is identical on both SDKs.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }

  s.source           = { :path => '.' }
  s.source_files = 'native_video_toolkit/Sources/native_video_toolkit/**/*', 'native_video_toolkit/Sources/native_video_toolkit_native/**/*'
  s.public_header_files = 'native_video_toolkit/Sources/native_video_toolkit_native/include/*.h'

  s.dependency 'Flutter'
  s.frameworks = 'AVFoundation', 'CoreMedia', 'CoreVideo'

  # Matches ffmpeg_kit_flutter_new's own minimum — see Package.swift's doc
  # comment on the same constant.
  s.platform = :ios, '14.0'

  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end
