// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.print.PrintAttributes$Builder`
extension type PrintAttributes$Builder._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Builder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Builder> type =
      $PrintAttributes$Builder$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Builder() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<PrintAttributes$Builder>();
  }
}

extension PrintAttributes$Builder$$Methods on PrintAttributes$Builder {
  static final _id_build = PrintAttributes$Builder._class.instanceMethodId(
    r'build',
    r'()Landroid/print/PrintAttributes;',
  );

  static final _build =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes build()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes? build() {
    return _build(
      reference.pointer,
      _id_build.pointer,
    ).object<PrintAttributes?>();
  }

  static final _id_setColorMode = PrintAttributes$Builder._class
      .instanceMethodId(
        r'setColorMode',
        r'(I)Landroid/print/PrintAttributes$Builder;',
      );

  static final _setColorMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setColorMode(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setColorMode(core$_.int i) {
    return _setColorMode(
      reference.pointer,
      _id_setColorMode.pointer,
      i,
    ).object<PrintAttributes$Builder?>();
  }

  static final _id_setDuplexMode = PrintAttributes$Builder._class
      .instanceMethodId(
        r'setDuplexMode',
        r'(I)Landroid/print/PrintAttributes$Builder;',
      );

  static final _setDuplexMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setDuplexMode(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setDuplexMode(core$_.int i) {
    return _setDuplexMode(
      reference.pointer,
      _id_setDuplexMode.pointer,
      i,
    ).object<PrintAttributes$Builder?>();
  }

  static final _id_setMediaSize = PrintAttributes$Builder._class.instanceMethodId(
    r'setMediaSize',
    r'(Landroid/print/PrintAttributes$MediaSize;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setMediaSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setMediaSize(android.print.PrintAttributes$MediaSize mediaSize)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setMediaSize(PrintAttributes$MediaSize? mediaSize) {
    final _$mediaSize = mediaSize?.reference ?? jni$_.jNullReference;
    return _setMediaSize(
      reference.pointer,
      _id_setMediaSize.pointer,
      _$mediaSize.pointer,
    ).object<PrintAttributes$Builder?>();
  }

  static final _id_setMinMargins = PrintAttributes$Builder._class.instanceMethodId(
    r'setMinMargins',
    r'(Landroid/print/PrintAttributes$Margins;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setMinMargins =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setMinMargins(android.print.PrintAttributes$Margins margins)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setMinMargins(PrintAttributes$Margins? margins) {
    final _$margins = margins?.reference ?? jni$_.jNullReference;
    return _setMinMargins(
      reference.pointer,
      _id_setMinMargins.pointer,
      _$margins.pointer,
    ).object<PrintAttributes$Builder?>();
  }

  static final _id_setResolution = PrintAttributes$Builder._class.instanceMethodId(
    r'setResolution',
    r'(Landroid/print/PrintAttributes$Resolution;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setResolution =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setResolution(android.print.PrintAttributes$Resolution resolution)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setResolution(
    PrintAttributes$Resolution? resolution,
  ) {
    final _$resolution = resolution?.reference ?? jni$_.jNullReference;
    return _setResolution(
      reference.pointer,
      _id_setResolution.pointer,
      _$resolution.pointer,
    ).object<PrintAttributes$Builder?>();
  }
}

final class $PrintAttributes$Builder$Type$
    extends jni$_.JType<PrintAttributes$Builder> {
  @jni$_.internal
  const $PrintAttributes$Builder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Builder;';
}

/// from: `android.print.PrintAttributes$Margins`
extension type PrintAttributes$Margins._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Margins',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Margins> type =
      $PrintAttributes$Margins$Type$();
  static final _id_NO_MARGINS = _class.staticFieldId(
    r'NO_MARGINS',
    r'Landroid/print/PrintAttributes$Margins;',
  );

  /// from: `static public final android.print.PrintAttributes$Margins NO_MARGINS`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$Margins? get NO_MARGINS =>
      _id_NO_MARGINS.getNullable(_class, PrintAttributes$Margins.type)
          as PrintAttributes$Margins?;

  static final _id_new$ = _class.constructorId(r'(IIII)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i, int i1, int i2, int i3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Margins(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
    core$_.int i3,
  ) {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      i,
      i1,
      i2,
      i3,
    ).object<PrintAttributes$Margins>();
  }
}

extension PrintAttributes$Margins$$Methods on PrintAttributes$Margins {
  static final _id_equals = PrintAttributes$Margins._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$bottomMils = PrintAttributes$Margins._class
      .instanceMethodId(r'getBottomMils', r'()I');

  static final _get$bottomMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getBottomMils()`
  core$_.int get bottomMils {
    return _get$bottomMils(
      reference.pointer,
      _id_get$bottomMils.pointer,
    ).integer;
  }

  static final _id_get$leftMils = PrintAttributes$Margins._class
      .instanceMethodId(r'getLeftMils', r'()I');

  static final _get$leftMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getLeftMils()`
  core$_.int get leftMils {
    return _get$leftMils(reference.pointer, _id_get$leftMils.pointer).integer;
  }

  static final _id_get$rightMils = PrintAttributes$Margins._class
      .instanceMethodId(r'getRightMils', r'()I');

  static final _get$rightMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getRightMils()`
  core$_.int get rightMils {
    return _get$rightMils(reference.pointer, _id_get$rightMils.pointer).integer;
  }

  static final _id_get$topMils = PrintAttributes$Margins._class
      .instanceMethodId(r'getTopMils', r'()I');

  static final _get$topMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getTopMils()`
  core$_.int get topMils {
    return _get$topMils(reference.pointer, _id_get$topMils.pointer).integer;
  }

  static final _id_hashCode$1 = PrintAttributes$Margins._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_toString$1 = PrintAttributes$Margins._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $PrintAttributes$Margins$Type$
    extends jni$_.JType<PrintAttributes$Margins> {
  @jni$_.internal
  const $PrintAttributes$Margins$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Margins;';
}

/// from: `android.print.PrintAttributes$MediaSize`
extension type PrintAttributes$MediaSize._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$MediaSize',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$MediaSize> type =
      $PrintAttributes$MediaSize$Type$();
  static final _id_ANSI_C = _class.staticFieldId(
    r'ANSI_C',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_C`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_C =>
      _id_ANSI_C.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ANSI_D = _class.staticFieldId(
    r'ANSI_D',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_D`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_D =>
      _id_ANSI_D.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ANSI_E = _class.staticFieldId(
    r'ANSI_E',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_E`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_E =>
      _id_ANSI_E.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ANSI_F = _class.staticFieldId(
    r'ANSI_F',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_F`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_F =>
      _id_ANSI_F.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A0 = _class.staticFieldId(
    r'ISO_A0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A0 =>
      _id_ISO_A0.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A1 = _class.staticFieldId(
    r'ISO_A1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A1 =>
      _id_ISO_A1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A10 = _class.staticFieldId(
    r'ISO_A10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A10 =>
      _id_ISO_A10.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A2 = _class.staticFieldId(
    r'ISO_A2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A2 =>
      _id_ISO_A2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A3 = _class.staticFieldId(
    r'ISO_A3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A3 =>
      _id_ISO_A3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A4 = _class.staticFieldId(
    r'ISO_A4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A4 =>
      _id_ISO_A4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A5 = _class.staticFieldId(
    r'ISO_A5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A5 =>
      _id_ISO_A5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A6 = _class.staticFieldId(
    r'ISO_A6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A6 =>
      _id_ISO_A6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A7 = _class.staticFieldId(
    r'ISO_A7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A7 =>
      _id_ISO_A7.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A8 = _class.staticFieldId(
    r'ISO_A8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A8 =>
      _id_ISO_A8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_A9 = _class.staticFieldId(
    r'ISO_A9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A9 =>
      _id_ISO_A9.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B0 = _class.staticFieldId(
    r'ISO_B0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B0 =>
      _id_ISO_B0.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B1 = _class.staticFieldId(
    r'ISO_B1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B1 =>
      _id_ISO_B1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B10 = _class.staticFieldId(
    r'ISO_B10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B10 =>
      _id_ISO_B10.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B2 = _class.staticFieldId(
    r'ISO_B2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B2 =>
      _id_ISO_B2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B3 = _class.staticFieldId(
    r'ISO_B3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B3 =>
      _id_ISO_B3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B4 = _class.staticFieldId(
    r'ISO_B4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B4 =>
      _id_ISO_B4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B5 = _class.staticFieldId(
    r'ISO_B5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B5 =>
      _id_ISO_B5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B6 = _class.staticFieldId(
    r'ISO_B6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B6 =>
      _id_ISO_B6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B7 = _class.staticFieldId(
    r'ISO_B7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B7 =>
      _id_ISO_B7.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B8 = _class.staticFieldId(
    r'ISO_B8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B8 =>
      _id_ISO_B8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_B9 = _class.staticFieldId(
    r'ISO_B9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B9 =>
      _id_ISO_B9.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C0 = _class.staticFieldId(
    r'ISO_C0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C0 =>
      _id_ISO_C0.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C1 = _class.staticFieldId(
    r'ISO_C1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C1 =>
      _id_ISO_C1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C10 = _class.staticFieldId(
    r'ISO_C10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C10 =>
      _id_ISO_C10.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C2 = _class.staticFieldId(
    r'ISO_C2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C2 =>
      _id_ISO_C2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C3 = _class.staticFieldId(
    r'ISO_C3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C3 =>
      _id_ISO_C3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C4 = _class.staticFieldId(
    r'ISO_C4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C4 =>
      _id_ISO_C4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C5 = _class.staticFieldId(
    r'ISO_C5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C5 =>
      _id_ISO_C5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C6 = _class.staticFieldId(
    r'ISO_C6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C6 =>
      _id_ISO_C6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C7 = _class.staticFieldId(
    r'ISO_C7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C7 =>
      _id_ISO_C7.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C8 = _class.staticFieldId(
    r'ISO_C8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C8 =>
      _id_ISO_C8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ISO_C9 = _class.staticFieldId(
    r'ISO_C9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C9 =>
      _id_ISO_C9.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B0 = _class.staticFieldId(
    r'JIS_B0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B0 =>
      _id_JIS_B0.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B1 = _class.staticFieldId(
    r'JIS_B1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B1 =>
      _id_JIS_B1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B10 = _class.staticFieldId(
    r'JIS_B10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B10 =>
      _id_JIS_B10.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B2 = _class.staticFieldId(
    r'JIS_B2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B2 =>
      _id_JIS_B2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B3 = _class.staticFieldId(
    r'JIS_B3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B3 =>
      _id_JIS_B3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B4 = _class.staticFieldId(
    r'JIS_B4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B4 =>
      _id_JIS_B4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B5 = _class.staticFieldId(
    r'JIS_B5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B5 =>
      _id_JIS_B5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B6 = _class.staticFieldId(
    r'JIS_B6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B6 =>
      _id_JIS_B6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B7 = _class.staticFieldId(
    r'JIS_B7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B7 =>
      _id_JIS_B7.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B8 = _class.staticFieldId(
    r'JIS_B8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B8 =>
      _id_JIS_B8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_B9 = _class.staticFieldId(
    r'JIS_B9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B9 =>
      _id_JIS_B9.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JIS_EXEC = _class.staticFieldId(
    r'JIS_EXEC',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_EXEC`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_EXEC =>
      _id_JIS_EXEC.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_CHOU2 = _class.staticFieldId(
    r'JPN_CHOU2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU2 =>
      _id_JPN_CHOU2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_CHOU3 = _class.staticFieldId(
    r'JPN_CHOU3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU3 =>
      _id_JPN_CHOU3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_CHOU4 = _class.staticFieldId(
    r'JPN_CHOU4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU4 =>
      _id_JPN_CHOU4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_HAGAKI = _class.staticFieldId(
    r'JPN_HAGAKI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_HAGAKI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_HAGAKI =>
      _id_JPN_HAGAKI.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_KAHU = _class.staticFieldId(
    r'JPN_KAHU',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_KAHU`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_KAHU =>
      _id_JPN_KAHU.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_KAKU2 = _class.staticFieldId(
    r'JPN_KAKU2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_KAKU2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_KAKU2 =>
      _id_JPN_KAKU2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_OE_PHOTO_L = _class.staticFieldId(
    r'JPN_OE_PHOTO_L',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_OE_PHOTO_L`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_OE_PHOTO_L =>
      _id_JPN_OE_PHOTO_L.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_OUFUKU = _class.staticFieldId(
    r'JPN_OUFUKU',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_OUFUKU`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_OUFUKU =>
      _id_JPN_OUFUKU.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_JPN_YOU4 = _class.staticFieldId(
    r'JPN_YOU4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_YOU4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_YOU4 =>
      _id_JPN_YOU4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_A = _class.staticFieldId(
    r'NA_ARCH_A',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_A`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_A =>
      _id_NA_ARCH_A.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_B = _class.staticFieldId(
    r'NA_ARCH_B',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_B`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_B =>
      _id_NA_ARCH_B.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_C = _class.staticFieldId(
    r'NA_ARCH_C',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_C`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_C =>
      _id_NA_ARCH_C.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_D = _class.staticFieldId(
    r'NA_ARCH_D',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_D`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_D =>
      _id_NA_ARCH_D.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_E = _class.staticFieldId(
    r'NA_ARCH_E',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_E`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_E =>
      _id_NA_ARCH_E.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_ARCH_E1 = _class.staticFieldId(
    r'NA_ARCH_E1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_E1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_E1 =>
      _id_NA_ARCH_E1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_FOOLSCAP = _class.staticFieldId(
    r'NA_FOOLSCAP',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_FOOLSCAP`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_FOOLSCAP =>
      _id_NA_FOOLSCAP.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_GOVT_LETTER = _class.staticFieldId(
    r'NA_GOVT_LETTER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_GOVT_LETTER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_GOVT_LETTER =>
      _id_NA_GOVT_LETTER.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_INDEX_3X5 = _class.staticFieldId(
    r'NA_INDEX_3X5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_3X5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_3X5 =>
      _id_NA_INDEX_3X5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_INDEX_4X6 = _class.staticFieldId(
    r'NA_INDEX_4X6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_4X6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_4X6 =>
      _id_NA_INDEX_4X6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_INDEX_5X8 = _class.staticFieldId(
    r'NA_INDEX_5X8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_5X8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_5X8 =>
      _id_NA_INDEX_5X8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_JUNIOR_LEGAL = _class.staticFieldId(
    r'NA_JUNIOR_LEGAL',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_JUNIOR_LEGAL`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_JUNIOR_LEGAL =>
      _id_NA_JUNIOR_LEGAL.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_LEDGER = _class.staticFieldId(
    r'NA_LEDGER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LEDGER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LEDGER =>
      _id_NA_LEDGER.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_LEGAL = _class.staticFieldId(
    r'NA_LEGAL',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LEGAL`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LEGAL =>
      _id_NA_LEGAL.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_LETTER = _class.staticFieldId(
    r'NA_LETTER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LETTER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LETTER =>
      _id_NA_LETTER.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_MONARCH = _class.staticFieldId(
    r'NA_MONARCH',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_MONARCH`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_MONARCH =>
      _id_NA_MONARCH.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_QUARTO = _class.staticFieldId(
    r'NA_QUARTO',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_QUARTO`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_QUARTO =>
      _id_NA_QUARTO.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_SUPER_B = _class.staticFieldId(
    r'NA_SUPER_B',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_SUPER_B`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_SUPER_B =>
      _id_NA_SUPER_B.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_NA_TABLOID = _class.staticFieldId(
    r'NA_TABLOID',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_TABLOID`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_TABLOID =>
      _id_NA_TABLOID.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_OM_DAI_PA_KAI = _class.staticFieldId(
    r'OM_DAI_PA_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_DAI_PA_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_DAI_PA_KAI =>
      _id_OM_DAI_PA_KAI.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_OM_JUURO_KU_KAI = _class.staticFieldId(
    r'OM_JUURO_KU_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_JUURO_KU_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_JUURO_KU_KAI =>
      _id_OM_JUURO_KU_KAI.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_OM_PA_KAI = _class.staticFieldId(
    r'OM_PA_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_PA_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_PA_KAI =>
      _id_OM_PA_KAI.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_1 = _class.staticFieldId(
    r'PRC_1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_1 =>
      _id_PRC_1.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_10 = _class.staticFieldId(
    r'PRC_10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_10 =>
      _id_PRC_10.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_16K = _class.staticFieldId(
    r'PRC_16K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_16K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_16K =>
      _id_PRC_16K.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_2 = _class.staticFieldId(
    r'PRC_2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_2 =>
      _id_PRC_2.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_3 = _class.staticFieldId(
    r'PRC_3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_3 =>
      _id_PRC_3.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_4 = _class.staticFieldId(
    r'PRC_4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_4 =>
      _id_PRC_4.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_5 = _class.staticFieldId(
    r'PRC_5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_5 =>
      _id_PRC_5.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_6 = _class.staticFieldId(
    r'PRC_6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_6 =>
      _id_PRC_6.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_7 = _class.staticFieldId(
    r'PRC_7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_7 =>
      _id_PRC_7.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_8 = _class.staticFieldId(
    r'PRC_8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_8 =>
      _id_PRC_8.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_PRC_9 = _class.staticFieldId(
    r'PRC_9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_9 =>
      _id_PRC_9.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ROC_16K = _class.staticFieldId(
    r'ROC_16K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ROC_16K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ROC_16K =>
      _id_ROC_16K.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_ROC_8K = _class.staticFieldId(
    r'ROC_8K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ROC_8K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ROC_8K =>
      _id_ROC_8K.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_UNKNOWN_LANDSCAPE = _class.staticFieldId(
    r'UNKNOWN_LANDSCAPE',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize UNKNOWN_LANDSCAPE`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get UNKNOWN_LANDSCAPE =>
      _id_UNKNOWN_LANDSCAPE.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_UNKNOWN_PORTRAIT = _class.staticFieldId(
    r'UNKNOWN_PORTRAIT',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize UNKNOWN_PORTRAIT`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get UNKNOWN_PORTRAIT =>
      _id_UNKNOWN_PORTRAIT.getNullable(_class, PrintAttributes$MediaSize.type)
          as PrintAttributes$MediaSize?;

  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;II)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$MediaSize(
    jni$_.JString? string,
    jni$_.JString? string1,
    core$_.int i,
    core$_.int i1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$string1.pointer,
      i,
      i1,
    ).object<PrintAttributes$MediaSize>();
  }
}

extension PrintAttributes$MediaSize$$Methods on PrintAttributes$MediaSize {
  static final _id_asLandscape = PrintAttributes$MediaSize._class
      .instanceMethodId(
        r'asLandscape',
        r'()Landroid/print/PrintAttributes$MediaSize;',
      );

  static final _asLandscape =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize asLandscape()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? asLandscape() {
    return _asLandscape(
      reference.pointer,
      _id_asLandscape.pointer,
    ).object<PrintAttributes$MediaSize?>();
  }

  static final _id_asPortrait = PrintAttributes$MediaSize._class
      .instanceMethodId(
        r'asPortrait',
        r'()Landroid/print/PrintAttributes$MediaSize;',
      );

  static final _asPortrait =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize asPortrait()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? asPortrait() {
    return _asPortrait(
      reference.pointer,
      _id_asPortrait.pointer,
    ).object<PrintAttributes$MediaSize?>();
  }

  static final _id_equals = PrintAttributes$MediaSize._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$heightMils = PrintAttributes$MediaSize._class
      .instanceMethodId(r'getHeightMils', r'()I');

  static final _get$heightMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getHeightMils()`
  core$_.int get heightMils {
    return _get$heightMils(
      reference.pointer,
      _id_get$heightMils.pointer,
    ).integer;
  }

  static final _id_get$id = PrintAttributes$MediaSize._class.instanceMethodId(
    r'getId',
    r'()Ljava/lang/String;',
  );

  static final _get$id =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get id {
    return _get$id(
      reference.pointer,
      _id_get$id.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_getLabel = PrintAttributes$MediaSize._class.instanceMethodId(
    r'getLabel',
    r'(Landroid/content/pm/PackageManager;)Ljava/lang/String;',
  );

  static final _getLabel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.String getLabel(android.content.pm.PackageManager packageManager)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getLabel(jni$_.JObject? packageManager) {
    final _$packageManager = packageManager?.reference ?? jni$_.jNullReference;
    return _getLabel(
      reference.pointer,
      _id_getLabel.pointer,
      _$packageManager.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$widthMils = PrintAttributes$MediaSize._class
      .instanceMethodId(r'getWidthMils', r'()I');

  static final _get$widthMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getWidthMils()`
  core$_.int get widthMils {
    return _get$widthMils(reference.pointer, _id_get$widthMils.pointer).integer;
  }

  static final _id_hashCode$1 = PrintAttributes$MediaSize._class
      .instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_get$isPortrait = PrintAttributes$MediaSize._class
      .instanceMethodId(r'isPortrait', r'()Z');

  static final _get$isPortrait =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isPortrait()`
  core$_.bool get isPortrait {
    return _get$isPortrait(
      reference.pointer,
      _id_get$isPortrait.pointer,
    ).boolean;
  }

  static final _id_toString$1 = PrintAttributes$MediaSize._class
      .instanceMethodId(r'toString', r'()Ljava/lang/String;');

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $PrintAttributes$MediaSize$Type$
    extends jni$_.JType<PrintAttributes$MediaSize> {
  @jni$_.internal
  const $PrintAttributes$MediaSize$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$MediaSize;';
}

/// from: `android.print.PrintAttributes$Resolution`
extension type PrintAttributes$Resolution._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Resolution',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Resolution> type =
      $PrintAttributes$Resolution$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;II)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Resolution(
    jni$_.JString? string,
    jni$_.JString? string1,
    core$_.int i,
    core$_.int i1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$string1.pointer,
      i,
      i1,
    ).object<PrintAttributes$Resolution>();
  }
}

extension PrintAttributes$Resolution$$Methods on PrintAttributes$Resolution {
  static final _id_equals = PrintAttributes$Resolution._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$horizontalDpi = PrintAttributes$Resolution._class
      .instanceMethodId(r'getHorizontalDpi', r'()I');

  static final _get$horizontalDpi =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getHorizontalDpi()`
  core$_.int get horizontalDpi {
    return _get$horizontalDpi(
      reference.pointer,
      _id_get$horizontalDpi.pointer,
    ).integer;
  }

  static final _id_get$id = PrintAttributes$Resolution._class.instanceMethodId(
    r'getId',
    r'()Ljava/lang/String;',
  );

  static final _get$id =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get id {
    return _get$id(
      reference.pointer,
      _id_get$id.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$label = PrintAttributes$Resolution._class
      .instanceMethodId(r'getLabel', r'()Ljava/lang/String;');

  static final _get$label =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getLabel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get label {
    return _get$label(
      reference.pointer,
      _id_get$label.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$verticalDpi = PrintAttributes$Resolution._class
      .instanceMethodId(r'getVerticalDpi', r'()I');

  static final _get$verticalDpi =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getVerticalDpi()`
  core$_.int get verticalDpi {
    return _get$verticalDpi(
      reference.pointer,
      _id_get$verticalDpi.pointer,
    ).integer;
  }

  static final _id_hashCode$1 = PrintAttributes$Resolution._class
      .instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_toString$1 = PrintAttributes$Resolution._class
      .instanceMethodId(r'toString', r'()Ljava/lang/String;');

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $PrintAttributes$Resolution$Type$
    extends jni$_.JType<PrintAttributes$Resolution> {
  @jni$_.internal
  const $PrintAttributes$Resolution$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Resolution;';
}

/// from: `android.print.PrintAttributes`
extension type PrintAttributes._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/print/PrintAttributes');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes> type = $PrintAttributes$Type$();

  /// from: `static public final int COLOR_MODE_COLOR`
  static const COLOR_MODE_COLOR = 2;

  /// from: `static public final int COLOR_MODE_MONOCHROME`
  static const COLOR_MODE_MONOCHROME = 1;
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator<android.print.PrintAttributes> CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject? get CREATOR =>
      _id_CREATOR.getNullable(_class, jni$_.JObject.type) as jni$_.JObject?;

  /// from: `static public final int DUPLEX_MODE_LONG_EDGE`
  static const DUPLEX_MODE_LONG_EDGE = 2;

  /// from: `static public final int DUPLEX_MODE_NONE`
  static const DUPLEX_MODE_NONE = 1;

  /// from: `static public final int DUPLEX_MODE_SHORT_EDGE`
  static const DUPLEX_MODE_SHORT_EDGE = 4;
}

extension PrintAttributes$$Methods on PrintAttributes {
  static final _id_describeContents = PrintAttributes._class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int describeContents()`
  core$_.int describeContents() {
    return _describeContents(
      reference.pointer,
      _id_describeContents.pointer,
    ).integer;
  }

  static final _id_equals = PrintAttributes._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_get$colorMode = PrintAttributes._class.instanceMethodId(
    r'getColorMode',
    r'()I',
  );

  static final _get$colorMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getColorMode()`
  core$_.int get colorMode {
    return _get$colorMode(reference.pointer, _id_get$colorMode.pointer).integer;
  }

  static final _id_get$duplexMode = PrintAttributes._class.instanceMethodId(
    r'getDuplexMode',
    r'()I',
  );

  static final _get$duplexMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getDuplexMode()`
  core$_.int get duplexMode {
    return _get$duplexMode(
      reference.pointer,
      _id_get$duplexMode.pointer,
    ).integer;
  }

  static final _id_get$mediaSize = PrintAttributes._class.instanceMethodId(
    r'getMediaSize',
    r'()Landroid/print/PrintAttributes$MediaSize;',
  );

  static final _get$mediaSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize getMediaSize()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? get mediaSize {
    return _get$mediaSize(
      reference.pointer,
      _id_get$mediaSize.pointer,
    ).object<PrintAttributes$MediaSize?>();
  }

  static final _id_get$minMargins = PrintAttributes._class.instanceMethodId(
    r'getMinMargins',
    r'()Landroid/print/PrintAttributes$Margins;',
  );

  static final _get$minMargins =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$Margins getMinMargins()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Margins? get minMargins {
    return _get$minMargins(
      reference.pointer,
      _id_get$minMargins.pointer,
    ).object<PrintAttributes$Margins?>();
  }

  static final _id_get$resolution = PrintAttributes._class.instanceMethodId(
    r'getResolution',
    r'()Landroid/print/PrintAttributes$Resolution;',
  );

  static final _get$resolution =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$Resolution getResolution()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Resolution? get resolution {
    return _get$resolution(
      reference.pointer,
      _id_get$resolution.pointer,
    ).object<PrintAttributes$Resolution?>();
  }

  static final _id_hashCode$1 = PrintAttributes._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_toString$1 = PrintAttributes._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_writeToParcel = PrintAttributes._class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(jni$_.JObject? parcel, core$_.int i) {
    final _$parcel = parcel?.reference ?? jni$_.jNullReference;
    _writeToParcel(
      reference.pointer,
      _id_writeToParcel.pointer,
      _$parcel.pointer,
      i,
    ).check();
  }
}

final class $PrintAttributes$Type$ extends jni$_.JType<PrintAttributes> {
  @jni$_.internal
  const $PrintAttributes$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes;';
}
