// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "native_video_toolkit",
    platforms: [
        // Matches ffmpeg_kit_flutter_new's own minimum (14.0) — this plugin
        // ships alongside it in every app that uses this toolkit
        // (compressVideo/generateThumbnail run through it on every
        // platform), and Xcode's SPM integration fails the whole app build
        // if any two plugins disagree on minimum platform version.
        .iOS("14.0")
    ],
    products: [
        .library(name: "native-video-toolkit", targets: ["native_video_toolkit", "native_video_toolkit_native"])
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .target(
            name: "native_video_toolkit",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ],
            resources: [
                // If your plugin requires a privacy manifest, for example if it collects user
                // data, update the PrivacyInfo.xcprivacy file to describe your plugin's
                // privacy impact, and then uncomment these lines. For more information, see
                // https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
                // .process("PrivacyInfo.xcprivacy"),

                // If you have other resources that need to be bundled with your plugin, refer to
                // the following instructions to add them:
                // https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package
            ]
        ),
        // Objective-C glue generated by tool/generate_bindings.dart. Kept in
        // its own target because SPM doesn't support mixing Swift and
        // Objective-C sources within a single target. Linking these
        // frameworks here (rather than relying on runtime dlopen) is what
        // makes their classes/symbols resolvable by the generated
        // `@Native`-annotated bindings.
        //
        // This is a byte-for-byte copy of macos/native_video_toolkit's own
        // native_video_toolkit_bindings.g.m — the bound AVFoundation/
        // CoreMedia/CoreVideo/CoreFoundation surface is identical between
        // the macOS and iOS SDKs (verified by generating against both and
        // diffing), so both platforms share the *same* generated Dart file
        // (lib/src/native_video_toolkit_bindings.g.dart) and the same glue
        // source — only the platform target/frameworks these are compiled
        // and linked into differ. See tool/generate_bindings.dart, which
        // regenerates both copies together so they never drift apart.
        .target(
            name: "native_video_toolkit_native",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ],
            publicHeadersPath: "include",
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
            ]
        )
    ]
)
