#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint native_video_toolkit.podspec` to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'native_video_toolkit'
  s.version          = '0.0.1'
  s.summary          = 'AVFoundation-backed compress/merge/mute/reverse video toolkit.'
  s.description      = <<-DESC
Direct AVFoundation bindings (compress/merge/mute/reverse) generated by
ffigen's Objective-C interop + package:objective_c — no hand-written native
code, no Dart MethodChannel. The Swift plugin class only exists to satisfy
Flutter's plugin registration.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }

  s.source           = { :path => '.' }
  s.source_files = 'native_video_toolkit/Sources/native_video_toolkit/**/*', 'native_video_toolkit/Sources/native_video_toolkit_native/**/*'
  s.public_header_files = 'native_video_toolkit/Sources/native_video_toolkit_native/include/*.h'

  s.dependency 'FlutterMacOS'
  s.frameworks = 'AVFoundation', 'CoreMedia', 'CoreVideo'

  s.platform = :osx, '10.15'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.swift_version = '5.0'
end
