import 'dart:async';
import 'dart:io';

import 'package:objective_c/objective_c.dart' as objc;
import 'package:path/path.dart' as p;

import 'src/native_video_toolkit_bindings.g.dart';
import 'src/cancel_token.dart';
import 'src/exceptions.dart';
import 'src/format_compat.dart';
import 'src/native_video_toolkit_android.dart';

export 'src/cancel_token.dart';
export 'src/exceptions.dart';

/// `kCVPixelFormatType_32BGRA` ('BGRA' as a big-endian four-char-code) —
/// CoreVideo defines this via a multi-char C literal in an enum that isn't
/// part of our bound surface, so the resolved integer value (a stable, public
/// part of the CoreVideo ABI) is used directly instead of adding a whole
/// extra enum just for one constant.
const int _kCVPixelFormatType32BGRA = 0x42475241;

/// Compress/merge/mute/reverse video, driven directly from Dart — via
/// AVFoundation bindings generated by ffigen's Objective-C interop on
/// macOS/iOS (`tool/generate_bindings.dart`), or via jnigen/`package:jni`
/// bindings to `android.media` on Android
/// (`tool/generate_android_bindings.dart`, see
/// `src/native_video_toolkit_android.dart`). No hand-written native code,
/// no method channel on either platform. Every method that differs by
/// platform picks the right implementation itself via `Platform.isAndroid`
/// — callers never branch on platform themselves; see each method's doc
/// for the exact native approach used on each side.
///
/// `compressVideo`/`generateThumbnail`/probing are the exception: they're
/// pure `ffmpeg_kit_flutter_new` calls with no AVFoundation/`android.media`
/// involvement at all, so the same code already runs unchanged on every
/// platform — nothing to dispatch there.
class NativeVideoToolkit {
  NativeVideoToolkit._();

  /// Re-encodes [inputPath]'s video track at [quality] (0.0 lowest .. 1.0
  /// highest) via a hardware (VideoToolbox) FFmpeg H.264 encode — see
  /// `src/format_compat.dart`'s `runCompressEncode`. Audio is copied through
  /// unchanged. The output is written in the *same container* as
  /// [inputPath] (e.g. compressing a `.mkv` produces a `.mkv`).
  ///
  /// The target bitrate is computed *relative to the source's own bitrate*
  /// (via `ProbedMediaInfo.estimatedVideoBitRate`), never a fixed constant —
  /// re-encoding against a fixed "highest quality" target regardless of how
  /// efficiently the source was already encoded is what previously made
  /// compressing an already-efficient HEVC file balloon it to over 20x its
  /// original size instead of shrinking it (H.264 needs roughly double
  /// HEVC's bitrate for equivalent quality, and "highest quality" ignored
  /// the source's bitrate entirely). This never targets a bitrate above the
  /// source's own, so compress can no longer make a file bigger.
  ///
  /// [inputPath] isn't limited to AVFoundation-native containers — FFmpeg
  /// decodes the source directly, so no `ensureAvFoundationCompatible`
  /// normalization pass is needed first (unlike merge/mute/reverse below,
  /// which stay on the AVFoundation pipeline and do need it).
  static Future<String> compressVideo({
    required String inputPath,
    required String outputPath,
    double quality = 1.0,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) async {
    cancelToken?.throwIfCancelled();
    final info = await probeMediaInfo(inputPath);
    final finalPath = _withExtensionOf(outputPath, inputPath);
    final targetBitRate = _targetBitRateForQuality(
      quality,
      info.estimatedVideoBitRate,
    );
    final scaleHeight = _scaleHeightForQuality(quality, info.height);

    final scratchMp4 = await newScratchFile(
      '${p.basenameWithoutExtension(outputPath)}.mp4',
    );
    await runCompressEncode(
      inputPath: inputPath,
      outputPath: scratchMp4.path,
      targetBitRate: targetBitRate,
      scaleHeight: scaleHeight,
      durationSeconds: info.durationSeconds,
      // Reserve the last stretch of the bar for the remux-to-target-container
      // step below, so the bar doesn't sit at 100% while that still runs.
      onProgress: onProgress == null ? null : (p) => onProgress(p * 0.95),
      cancelToken: cancelToken,
    );
    final result = await remuxToMatchFormat(
      scratchMp4,
      finalPath,
      cancelToken: cancelToken,
    );
    onProgress?.call(1.0);
    return result.path;
  }

  /// Concatenates [inputPaths], in order, into a single video at
  /// [outputPath] using `AVMutableComposition`. A clip with no audio track
  /// contributes silence for its duration rather than failing the merge.
  ///
  /// Each entry in [inputPaths] is independently normalized to an
  /// AVFoundation-compatible container first if needed — see
  /// [compressVideo]'s doc and `src/format_compat.dart`.
  ///
  /// Dispatches to [NativeVideoToolkitAndroid.mergeVideos] on Android —
  /// this class's whole job on every platform is picking the right native
  /// media stack transparently, so callers never need their own
  /// `Platform.isAndroid` checks.
  static Future<String> mergeVideos({
    required List<String> inputPaths,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) {
    if (Platform.isAndroid) {
      return NativeVideoToolkitAndroid.mergeVideos(
        inputPaths: inputPaths,
        outputPath: outputPath,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
    }
    return _mergeVideosAvFoundation(
      inputPaths: inputPaths,
      outputPath: outputPath,
      onProgress: onProgress,
      cancelToken: cancelToken,
    );
  }

  static Future<String> _mergeVideosAvFoundation({
    required List<String> inputPaths,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) async {
    if (inputPaths.isEmpty) {
      throw const VideoToolException('No input files provided.');
    }

    // Run independently — merge is the one operation with multiple inputs,
    // so any that need an FFmpeg remux/re-encode (see
    // ensureAvFoundationCompatible) shouldn't wait on each other one at a
    // time.
    final normalized = await Future.wait([
      for (final path in inputPaths)
        ensureAvFoundationCompatible(File(path), cancelToken: cancelToken),
    ]);
    try {
      cancelToken?.throwIfCancelled();
      _deleteIfExists(outputPath);

      final composition = AVMutableComposition.composition();
      final videoTrack = composition.addMutableTrackWithMediaType(
        AVMediaTypeVideo,
        preferredTrackID: 0,
      );
      if (videoTrack == null) {
        throw const VideoToolException('Could not create a composition track.');
      }
      // Created lazily, only once some clip actually has audio — a
      // composition track added up front but never given any segments (e.g.
      // every input is silent) makes AVAssetExportSession fail the whole
      // export with AVErrorOperationNotSupportedForAsset (-11838).
      AVMutableCompositionTrack? audioTrack;

      var cursor = kCMTimeZero;
      CGAffineTransform? transform;

      for (var i = 0; i < normalized.length; i++) {
        final asset = AVURLAsset.URLAssetWithURL(_fileUrl(normalized[i].path));
        final range = CMTimeRangeMake(kCMTimeZero, asset.duration);

        final videoTracks = _tracksOfType(asset, AVMediaTypeVideo);
        if (videoTracks.isNotEmpty) {
          try {
            videoTrack.insertTimeRange(
              range,
              ofTrack: videoTracks.first,
              atTime: cursor,
            );
            transform ??= videoTracks.first.preferredTransform;
          } on objc.NSErrorException catch (e) {
            throw VideoToolException(
              'Failed to add "${inputPaths[i]}" to the merge: '
              '${e.error.localizedDescription.toDartString()}',
            );
          }
        }

        final audioTracks = _tracksOfType(asset, AVMediaTypeAudio);
        if (audioTracks.isNotEmpty) {
          audioTrack ??= composition.addMutableTrackWithMediaType(
            AVMediaTypeAudio,
            preferredTrackID: 0,
          );
          try {
            audioTrack?.insertTimeRange(
              range,
              ofTrack: audioTracks.first,
              atTime: cursor,
            );
          } on objc.NSErrorException {
            // A clip missing/failing on audio shouldn't sink the whole merge —
            // the result is just silent for that segment.
          }
        }

        cursor = CMTimeAdd(cursor, asset.duration);
      }

      if (transform != null) {
        videoTrack.preferredTransform = transform;
      }

      // Passthrough re-muxes the existing encoded samples with no
      // re-encoding — for a plain concatenation (no trimming/transform work
      // beyond carrying over `preferredTransform`) this is what makes a
      // merge of long clips take seconds instead of minutes. AVFoundation
      // returns a nil session for `initWithAsset:presetName:` when the
      // preset isn't compatible with the asset (e.g. clips with differing
      // encoding parameters that genuinely need re-encoding to produce one
      // consistent output stream) — in that case fall back to a real
      // re-encode via HighestQuality.
      final session =
          AVAssetExportSession.alloc().initWithAsset(
            composition,
            presetName: AVAssetExportPresetPassthrough,
          ) ??
          AVAssetExportSession.alloc().initWithAsset(
            composition,
            presetName: AVAssetExportPresetHighestQuality,
          );
      if (session == null) {
        throw const VideoToolException('Could not create an export session.');
      }

      // Matches the *first* clip's container — there's no single "the"
      // input to match when merging, and defaulting to the primary/first
      // clip's format is the convention most editors use.
      return await _exportAndMatchFormat(
        session: session,
        outputPath: outputPath,
        originalInputPath: inputPaths.first,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
    } finally {
      for (var i = 0; i < normalized.length; i++) {
        await _cleanupIfTemp(normalized[i], inputPaths[i]);
      }
    }
  }

  /// Re-exports [inputPath] with its audio track dropped, by copying only
  /// the video track into a fresh `AVMutableComposition`.
  ///
  /// See [compressVideo]'s doc — non-AVFoundation-native containers are
  /// normalized first. Dispatches to [NativeVideoToolkitAndroid.muteVideo]
  /// on Android — see [mergeVideos]'s doc.
  static Future<String> muteVideo({
    required String inputPath,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) {
    if (Platform.isAndroid) {
      return NativeVideoToolkitAndroid.muteVideo(
        inputPath: inputPath,
        outputPath: outputPath,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
    }
    return _muteVideoAvFoundation(
      inputPath: inputPath,
      outputPath: outputPath,
      onProgress: onProgress,
      cancelToken: cancelToken,
    );
  }

  static Future<String> _muteVideoAvFoundation({
    required String inputPath,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) async {
    final normalized = await ensureAvFoundationCompatible(
      File(inputPath),
      cancelToken: cancelToken,
    );
    try {
      cancelToken?.throwIfCancelled();
      final asset = AVURLAsset.URLAssetWithURL(_fileUrl(normalized.path));
      final sourceTracks = _tracksOfType(asset, AVMediaTypeVideo);
      if (sourceTracks.isEmpty) {
        throw const VideoToolException('No video track found in this file.');
      }
      final sourceTrack = sourceTracks.first;

      final composition = AVMutableComposition.composition();
      final videoTrack = composition.addMutableTrackWithMediaType(
        AVMediaTypeVideo,
        preferredTrackID: 0,
      );
      if (videoTrack == null) {
        throw const VideoToolException('Could not create a composition track.');
      }

      try {
        videoTrack.insertTimeRange(
          CMTimeRangeMake(kCMTimeZero, asset.duration),
          ofTrack: sourceTrack,
          atTime: kCMTimeZero,
        );
      } on objc.NSErrorException catch (e) {
        throw VideoToolException(
          'Could not mute this file: ${e.error.localizedDescription.toDartString()}',
        );
      }
      videoTrack.preferredTransform = sourceTrack.preferredTransform;

      // Passthrough, same reasoning as mergeVideos: the video samples
      // aren't touched at all (only the audio track is dropped), so this
      // never needed a full re-encode either.
      final session =
          AVAssetExportSession.alloc().initWithAsset(
            composition,
            presetName: AVAssetExportPresetPassthrough,
          ) ??
          AVAssetExportSession.alloc().initWithAsset(
            composition,
            presetName: AVAssetExportPresetHighestQuality,
          );
      if (session == null) {
        throw const VideoToolException('Could not create an export session.');
      }

      return await _exportAndMatchFormat(
        session: session,
        outputPath: outputPath,
        originalInputPath: inputPath,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
    } finally {
      await _cleanupIfTemp(normalized, inputPath);
    }
  }

  /// Reverses the video track of [inputPath] frame-by-frame via
  /// `AVAssetReader`/`AVAssetWriter` so playback runs backwards.
  ///
  /// This decodes every frame into memory before writing the reversed
  /// output — correct and simple, but memory-heavy for long videos; there is
  /// no streaming/ring-buffer version of this. The output has no audio
  /// track: sample-accurate audio reversal is a separate, much larger
  /// problem and is out of scope here.
  ///
  /// See [compressVideo]'s doc — non-AVFoundation-native containers are
  /// normalized first. Dispatches to
  /// [NativeVideoToolkitAndroid.reverseVideo] on Android (a `MediaCodec`
  /// decode/encode of the same shape, also with no audio track) — see
  /// [mergeVideos]'s doc.
  static Future<String> reverseVideo({
    required String inputPath,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) {
    if (Platform.isAndroid) {
      return NativeVideoToolkitAndroid.reverseVideo(
        inputPath: inputPath,
        outputPath: outputPath,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
    }
    return _reverseVideoAvFoundation(
      inputPath: inputPath,
      outputPath: outputPath,
      onProgress: onProgress,
      cancelToken: cancelToken,
    );
  }

  static Future<String> _reverseVideoAvFoundation({
    required String inputPath,
    required String outputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) async {
    final normalized = await ensureAvFoundationCompatible(
      File(inputPath),
      cancelToken: cancelToken,
    );
    try {
      return await _reverseVideoImpl(
        normalized.path,
        outputPath,
        inputPath,
        onProgress,
        cancelToken,
      );
    } finally {
      await _cleanupIfTemp(normalized, inputPath);
    }
  }

  static Future<String> _reverseVideoImpl(
    String inputPath,
    String outputPath,
    String originalInputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    final asset = AVURLAsset.URLAssetWithURL(_fileUrl(inputPath));
    final videoTracks = _tracksOfType(asset, AVMediaTypeVideo);
    if (videoTracks.isEmpty) {
      throw const VideoToolException('No video track found in this file.');
    }
    final videoTrack = videoTracks.first;

    // This implementation decodes every frame into memory up front (see
    // method doc) — for a 1920x1080 clip that's ~8MB *per frame*, so a
    // feature-length or even few-minutes-long video can demand tens of GB
    // and hang/crash the app trying to allocate it, rather than failing
    // fast. Estimate the decoded footprint before touching the reader at
    // all and reject clips that would blow past a sane budget, with a
    // concrete "how long a clip is safe at this resolution" message instead
    // of a vague failure after the user has already waited.
    final naturalSize = videoTrack.naturalSize;
    final fps = videoTrack.nominalFrameRate > 0
        ? videoTrack.nominalFrameRate
        : 30.0;
    final durationSeconds = asset.duration.timescale > 0
        ? asset.duration.value / asset.duration.timescale
        : 0.0;
    final estimatedFrameCount = (durationSeconds * fps).round();
    final bytesPerFrame = naturalSize.width * naturalSize.height * 4;
    const maxDecodedBytes = 3 * 1024 * 1024 * 1024; // 3 GB
    if (bytesPerFrame > 0 &&
        estimatedFrameCount * bytesPerFrame > maxDecodedBytes) {
      final maxSeconds = (maxDecodedBytes / bytesPerFrame / fps).floor();
      throw VideoToolException(
        'This video is too long to reverse at its resolution '
        '(${naturalSize.width.round()}x${naturalSize.height.round()}) — reverse '
        'decodes every frame into memory, and this clip would need too much '
        'of it. Clips up to about ${maxSeconds}s at this resolution are '
        'supported; try a shorter clip or compress it first.',
      );
    }

    final AVAssetReader reader;
    try {
      final r = AVAssetReader.alloc().initWithAsset(asset);
      if (r == null) {
        throw const VideoToolException('Could not create an asset reader.');
      }
      reader = r;
    } on objc.NSErrorException catch (e) {
      throw VideoToolException(
        'Could not create an asset reader: '
        '${e.error.localizedDescription.toDartString()}',
      );
    }

    final readerOutputSettings = objc.NSMutableDictionary.of({
      kCVPixelBufferPixelFormatTypeKey.toNSString(): _kCVPixelFormatType32BGRA
          .toNSNumber(),
    });
    final trackOutput = AVAssetReaderTrackOutput.alloc().initWithTrack(
      videoTrack,
      outputSettings: readerOutputSettings,
    );
    if (!reader.canAddOutput(trackOutput)) {
      throw const VideoToolException(
        'Could not read the video track of this file.',
      );
    }
    reader.addOutput(trackOutput);
    if (!reader.startReading()) {
      throw VideoToolException(
        reader.error?.localizedDescription.toDartString() ??
            'Failed to start reading.',
      );
    }

    // Decode every frame up front (see method doc for the memory caveat).
    // Untyped on purpose: `CVPixelBufferRetain` returns `Pointer<__CVBuffer>`,
    // but `__CVBuffer` is a leading-underscore name generated inside
    // native_video_toolkit_bindings.g.dart — Dart's per-library privacy makes
    // it unnameable from this file, even though the type itself is usable.
    final frames = <dynamic>[];
    var frameDuration = kCMTimeZero;
    var haveDuration = false;

    void releaseFrames() {
      for (final frame in frames) {
        CVPixelBufferRelease(frame);
      }
    }

    // Every iteration here is a synchronous FFI call with no `await` in
    // between, which (unlike the AVAssetExportSession-based operations
    // elsewhere in this file, which run their heavy lifting asynchronously
    // on a native queue) blocks the calling isolate — the one Flutter's UI
    // runs on — for the entire decode phase. With no yield point, a clip of
    // more than a few hundred frames reads as a fully frozen app (no
    // spinner animation, no window redraws) rather than "working." Yielding
    // every 15 frames keeps the engine's event loop serviced without
    // meaningfully slowing decode throughput.
    var framesSinceYield = 0;
    // Decode is the first half of the operation, write is the second —
    // `estimatedFrameCount` (from the memory-budget check above) is only an
    // estimate, so clamp rather than let it overshoot 0.5 if the real count
    // runs a little ahead of it.
    while (true) {
      final sampleBuffer = trackOutput.copyNextSampleBuffer();
      if (sampleBuffer.address == 0) break;

      final imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
      if (imageBuffer.address != 0) {
        frames.add(CVPixelBufferRetain(imageBuffer));
        if (!haveDuration) {
          final duration = CMSampleBufferGetDuration(sampleBuffer);
          if (duration.value > 0) {
            frameDuration = duration;
            haveDuration = true;
          }
        }
      }
      CFRelease(sampleBuffer.cast());

      if (++framesSinceYield >= 15) {
        framesSinceYield = 0;
        if (onProgress != null && estimatedFrameCount > 0) {
          onProgress((frames.length / estimatedFrameCount / 2).clamp(0.0, 0.5));
        }
        await Future<void>.delayed(Duration.zero);
        if (cancelToken?.isCancelled ?? false) {
          releaseFrames();
          cancelToken!.throwIfCancelled();
        }
      }
    }

    if (reader.status == AVAssetReaderStatus.AVAssetReaderStatusFailed) {
      releaseFrames();
      final underlying = reader.error?.localizedDescription.toDartString();
      // `ensureAvFoundationCompatible` only checks the codec *name*
      // (h264/hevc/etc.) — it can't see profile/bit-depth, so a 10-bit or
      // HDR-profile HEVC stream passes that check yet still can't be
      // decoded here, since this reader always requests plain 8-bit BGRA
      // output. That's the common real cause behind a generic "Cannot
      // Decode" at this point, so point the user at the one thing that
      // reliably fixes it: re-encoding via Compress first.
      throw VideoToolException(
        '${underlying ?? 'Failed while reading frames.'} This can happen '
        'with some HEVC/HDR video profiles reverse can\'t decode directly — '
        'try Compress Video on this file first, then Reverse the compressed '
        'result.',
      );
    }
    if (frames.isEmpty) {
      throw const VideoToolException(
        'No frames could be decoded from this file.',
      );
    }
    if (!haveDuration) {
      frameDuration = CMTimeMake(1, fps.round());
    }

    // Writer output: directly into the original container when AVFoundation
    // can write it, otherwise into a scratch mp4 that gets remuxed into the
    // original container as a final step (see the `return` below).
    final nativeType = _avFileTypeFor(originalInputPath);
    final directOutputPath = _withExtensionOf(outputPath, originalInputPath);
    final writerOutputFile = nativeType != null
        ? File(directOutputPath)
        : await newScratchFile('${p.basenameWithoutExtension(outputPath)}.mp4');
    _deleteIfExists(writerOutputFile.path);

    final AVAssetWriter writer;
    try {
      final w = AVAssetWriter.alloc().initWithURL(
        _fileUrl(writerOutputFile.path),
        fileType: nativeType ?? AVFileTypeMPEG4,
      );
      if (w == null) {
        releaseFrames();
        throw const VideoToolException('Could not create an asset writer.');
      }
      writer = w;
    } on objc.NSErrorException catch (e) {
      releaseFrames();
      throw VideoToolException(
        'Could not create an asset writer: '
        '${e.error.localizedDescription.toDartString()}',
      );
    }

    final videoSettings = objc.NSMutableDictionary.of({
      AVVideoCodecKey: AVVideoCodecTypeH264,
      AVVideoWidthKey: naturalSize.width.round().toNSNumber(),
      AVVideoHeightKey: naturalSize.height.round().toNSNumber(),
    });
    final writerInput = AVAssetWriterInput.assetWriterInputWithMediaType(
      AVMediaTypeVideo,
      outputSettings: videoSettings,
    );
    writerInput.expectsMediaDataInRealTime = false;
    // Bake the source's rotation metadata into the output so reversed
    // portrait/landscape clips still play the right way up — the reader
    // above hands back raw, untransformed pixel data.
    writerInput.transform = videoTrack.preferredTransform;

    final adaptorAttributes = objc.NSMutableDictionary.of({
      kCVPixelBufferPixelFormatTypeKey.toNSString(): _kCVPixelFormatType32BGRA
          .toNSNumber(),
    });
    final adaptor =
        AVAssetWriterInputPixelBufferAdaptor.assetWriterInputPixelBufferAdaptorWithAssetWriterInput(
          writerInput,
          sourcePixelBufferAttributes: adaptorAttributes,
        );

    if (!writer.canAddInput(writerInput)) {
      releaseFrames();
      throw const VideoToolException('Could not add a writer input.');
    }
    writer.addInput(writerInput);
    if (!writer.startWriting()) {
      releaseFrames();
      throw VideoToolException(
        writer.error?.localizedDescription.toDartString() ??
            'Failed to start writing.',
      );
    }
    writer.startSessionAtSourceTime(kCMTimeZero);

    // No streaming pull callback (`requestMediaDataWhenReadyOnQueue:`) —
    // the whole frame list already lives in memory from the read phase
    // above, so a simple poll-and-append loop is both correct and much
    // simpler than driving this from a repeating native callback.
    var presentationTime = kCMTimeZero;
    var framesSinceWriteYield = 0;
    final totalFrames = frames.length;
    for (var i = totalFrames - 1; i >= 0; i--) {
      while (!writerInput.isReadyForMoreMediaData) {
        await Future<void>.delayed(const Duration(milliseconds: 5));
      }
      adaptor.appendPixelBuffer(
        frames[i],
        withPresentationTime: presentationTime,
      );
      presentationTime = CMTimeAdd(presentationTime, frameDuration);

      // Backpressure above usually yields regularly on its own, but isn't
      // guaranteed to on every resolution/hardware combination — an
      // explicit periodic yield here too keeps the UI isolate serviced
      // either way (see the matching comment on the read loop above).
      if (++framesSinceWriteYield >= 15) {
        framesSinceWriteYield = 0;
        onProgress?.call(0.5 + (totalFrames - i) / totalFrames / 2);
        await Future<void>.delayed(Duration.zero);
        if (cancelToken?.isCancelled ?? false) {
          releaseFrames();
          _deleteIfExists(writerOutputFile.path);
          cancelToken!.throwIfCancelled();
        }
      }
    }
    onProgress?.call(1.0);
    writerInput.markAsFinished();
    releaseFrames();

    final completer = Completer<void>();
    writer.finishWritingWithCompletionHandler(
      ObjCBlock_ffiVoid.listener(completer.complete),
    );
    await completer.future;

    if (writer.status != AVAssetWriterStatus.AVAssetWriterStatusCompleted) {
      throw VideoToolException(
        writer.error?.localizedDescription.toDartString() ??
            'Failed to finish writing.',
      );
    }

    if (nativeType != null) {
      return writerOutputFile.path;
    }
    // AVFoundation could only write mp4 — remux that into the container the
    // original file was in.
    final result = await remuxToMatchFormat(writerOutputFile, directOutputPath);
    return result.path;
  }

  /// For a video *player*, not a processing tool: returns a path guaranteed
  /// to open in an AVFoundation-based player (e.g. `package:video_player`,
  /// which uses `AVPlayer` under the hood on macOS/iOS and therefore has
  /// exactly the same container support as everything else in this
  /// package). Returns [inputPath] unchanged when it's already
  /// AVFoundation-native; otherwise remuxes/transcodes it to a scratch mp4
  /// first, same as every processing method here.
  ///
  /// Unlike `compressVideo`/etc., there's no "done, delete the scratch
  /// file" moment — playback holds it open for as long as the user is
  /// watching. Callers that get back a path different from [inputPath] own
  /// deleting it (its parent directory, specifically) once playback ends;
  /// [isTemporaryPlayableCopy] tells you which case you're in. Dispatches
  /// to [NativeVideoToolkitAndroid.ensurePlayableCopy] on Android (the
  /// `video_player` plugin uses ExoPlayer/media3 there, with much broader
  /// native container support than AVFoundation) — see [mergeVideos]'s doc.
  static Future<String> ensurePlayableCopy(String inputPath) {
    if (Platform.isAndroid) {
      return NativeVideoToolkitAndroid.ensurePlayableCopy(inputPath);
    }
    return _ensurePlayableCopyAvFoundation(inputPath);
  }

  static Future<String> _ensurePlayableCopyAvFoundation(
    String inputPath,
  ) async {
    final normalized = await ensureAvFoundationCompatible(File(inputPath));
    return normalized.path;
  }

  /// Whether [path] (as returned by [ensurePlayableCopy]) is a scratch copy
  /// the caller is responsible for cleaning up, vs. the original input
  /// returned unchanged.
  static bool isTemporaryPlayableCopy(String path, String originalInputPath) =>
      path != originalInputPath;

  /// Deletes a temporary copy produced by [ensurePlayableCopy] (its whole
  /// scratch directory, not just the file). No-ops if [path] wasn't
  /// actually a temporary copy.
  static Future<void> disposePlayableCopy(
    String path,
    String originalInputPath,
  ) => _cleanupIfTemp(File(path), originalInputPath);

  /// Generates a small JPEG preview frame from [inputPath] (any container
  /// FFmpeg can read — no AVFoundation compatibility normalization needed
  /// since this only reads, never hands the file to `AVAssetReader`/
  /// `AVPlayer`), written to a fresh scratch file. For showing a real
  /// thumbnail in upload/preview UI instead of a placeholder icon.
  static Future<String> generateThumbnail(String inputPath) async {
    final output = await newScratchFile('thumbnail.jpg');
    await extractThumbnail(inputPath, output.path);
    return output.path;
  }

  // ---- internal ----

  static objc.NSURL _fileUrl(String path) =>
      objc.NSURL.fileURLWithPath(objc.NSString(path));

  static void _deleteIfExists(String path) {
    final file = File(path);
    if (file.existsSync()) file.deleteSync();
  }

  /// Returns the AVFoundation file type matching [path]'s extension, or
  /// `null` if AVFoundation has no native writer for it (in which case the
  /// caller exports to a scratch mp4 and remuxes with [remuxToMatchFormat]).
  /// Kept in sync with `format_compat.dart`'s `avFoundationNativeExtensions`.
  static objc.NSString? _avFileTypeFor(String path) {
    switch (p.extension(path).replaceFirst('.', '').toLowerCase()) {
      case 'mp4':
        return AVFileTypeMPEG4;
      case 'mov':
        return AVFileTypeQuickTimeMovie;
      case 'm4v':
        return AVFileTypeAppleM4V;
      case '3gp':
        return AVFileType3GPP;
      case '3g2':
        return AVFileType3GPP2;
      default:
        return null;
    }
  }

  /// [outputPath] with its extension swapped for [originalPath]'s, so a
  /// caller-provided output path (which may have been built without
  /// knowing the source format) still lands on the right container.
  static String _withExtensionOf(String outputPath, String originalPath) {
    final ext = p.extension(originalPath);
    return ext.isEmpty ? outputPath : p.setExtension(outputPath, ext);
  }

  /// Runs [session], exporting directly to [outputPath] (with its
  /// extension matched to [originalInputPath]'s container) when
  /// AVFoundation can write that container natively, or to a scratch mp4
  /// first and remuxing into it otherwise. Returns the final output path.
  static Future<String> _exportAndMatchFormat({
    required AVAssetExportSession session,
    required String outputPath,
    required String originalInputPath,
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) async {
    final nativeType = _avFileTypeFor(originalInputPath);
    final finalPath = _withExtensionOf(outputPath, originalInputPath);

    if (nativeType != null) {
      _deleteIfExists(finalPath);
      session.outputURL = _fileUrl(finalPath);
      session.outputFileType = nativeType;
      await _runExportSession(
        session,
        onProgress: onProgress,
        cancelToken: cancelToken,
      );
      return finalPath;
    }

    final scratchMp4 = await newScratchFile(
      '${p.basenameWithoutExtension(outputPath)}.mp4',
    );
    session.outputURL = _fileUrl(scratchMp4.path);
    session.outputFileType = AVFileTypeMPEG4;
    await _runExportSession(
      session,
      onProgress: onProgress,
      cancelToken: cancelToken,
    );

    final result = await remuxToMatchFormat(
      scratchMp4,
      finalPath,
      cancelToken: cancelToken,
    );
    return result.path;
  }

  /// Deletes the scratch directory [normalized] lives in, but only if it
  /// actually *is* a scratch file — i.e. [ensureAvFoundationCompatible]
  /// didn't just hand back the original, already-compatible input.
  static Future<void> _cleanupIfTemp(
    File normalized,
    String originalInputPath,
  ) async {
    if (normalized.path == originalInputPath) return;
    final dir = normalized.parent;
    if (await dir.exists()) {
      await dir.delete(recursive: true);
    }
  }

  static List<AVAssetTrack> _tracksOfType(
    AVAsset asset,
    objc.NSString mediaType,
  ) {
    final array = asset.tracksWithMediaType(mediaType);
    return [for (final obj in array.asDart()) AVAssetTrack.as(obj)];
  }

  /// The compress target bitrate, as a fraction of [sourceBitRate] — never
  /// above it, so compress can never make a file bigger than its source.
  /// Falls back to a flat per-tier default only when [sourceBitRate]
  /// couldn't be determined at all (see [ProbedMediaInfo.estimatedVideoBitRate]).
  static int _targetBitRateForQuality(double quality, int? sourceBitRate) {
    final (factor, fallback) = switch (quality) {
      >= 0.9 => (0.85, 8000000),
      >= 0.6 => (0.6, 5000000),
      >= 0.3 => (0.4, 2500000),
      _ => (0.25, 1000000),
    };
    if (sourceBitRate == null || sourceBitRate <= 0) return fallback;
    final target = (sourceBitRate * factor).round();
    // A floor purely to avoid a degenerate near-zero encode request — not a
    // quality decision. This used to be 150000, which for a genuinely
    // low-bitrate source (some efficiently-encoded HEVC rips average well
    // under 100kbps) silently overrode a correct, *lower* computed target
    // with a higher one — precisely backwards for "never exceed the
    // source," and part of why compressing one such file still landed at
    // ~118% of its original size instead of shrinking it.
    return target < 20000 ? 20000 : target;
  }

  /// The resolution cap for [quality] (height in pixels), or `null` for no
  /// cap. Never upscales — returns `null` when [sourceHeight] is already at
  /// or below the tier's cap.
  static int? _scaleHeightForQuality(double quality, int? sourceHeight) {
    final cap = switch (quality) {
      >= 0.9 => null,
      >= 0.6 => 1080,
      >= 0.3 => 720,
      _ => 480,
    };
    if (cap == null) return null;
    if (sourceHeight != null && sourceHeight <= cap) return null;
    return cap;
  }

  static Future<void> _runExportSession(
    AVAssetExportSession session, {
    void Function(double progress)? onProgress,
    CancelToken? cancelToken,
  }) {
    cancelToken?.throwIfCancelled();
    final completer = Completer<void>();
    session.exportAsynchronouslyWithCompletionHandler(
      ObjCBlock_ffiVoid.listener(() {
        switch (session.status) {
          case AVAssetExportSessionStatus.AVAssetExportSessionStatusCompleted:
            completer.complete();
          case AVAssetExportSessionStatus.AVAssetExportSessionStatusCancelled:
            completer.completeError(
              const VideoToolException('Export was cancelled.'),
            );
          default:
            completer.completeError(
              VideoToolException(
                session.error?.localizedDescription.toDartString() ??
                    'Export failed.',
              ),
            );
        }
      }),
    );

    // Lets `cancelToken.cancel()` stop *this* export directly — otherwise a
    // cancellation request made while an AVAssetExportSession is running
    // would only be noticed the next time this toolkit checks
    // `throwIfCancelled()` between steps, i.e. not until the export the
    // user is trying to stop has already finished on its own.
    cancelToken?.attach(session.cancelExport);

    // `exportAsynchronouslyWithCompletionHandler:` only calls back once, at
    // the end — this is the only way to see it's *doing* something in the
    // meantime. A long export (long source, no downscale) with zero visible
    // feedback beyond a spinner is exactly what reads as "hung"/"not
    // working" even though it's progressing normally.
    Timer? poll;
    if (onProgress != null) {
      poll = Timer.periodic(const Duration(milliseconds: 250), (_) {
        onProgress(session.progress.clamp(0.0, 1.0));
      });
      completer.future.whenComplete(() => poll?.cancel());
    }

    completer.future.whenComplete(() => cancelToken?.detach());

    return completer.future;
  }
}
