// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/print/PrintAttributes.dart' as printattributes$_;

import '../../../android/print/PrintDocumentAdapter.dart'
    as printdocumentadapter$_;

import '../../../android/webkit/WebView.dart' as webview$_;

import '../../../java/io/File.dart' as file$_;

/// from: `com.example.native_pdf_engine.PdfPrinter$Callback`
extension type PdfPrinter$Callback._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/PdfPrinter$Callback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfPrinter$Callback> type =
      $PdfPrinter$Callback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $PdfPrinter$Callback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onSuccess(Ljava/lang/String;)V') {
        _$impls[$p]!.onSuccess(($a![0] as jni$_.JString));
        return jni$_.nullptr;
      }
      if ($d == r'onFailure()V') {
        _$impls[$p]!.onFailure();
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $PdfPrinter$Callback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.example.native_pdf_engine.PdfPrinter$Callback',
      $p,
      _$invokePointer,
      [
        if ($impl.onSuccess$async) r'onSuccess(Ljava/lang/String;)V',
        if ($impl.onFailure$async) r'onFailure()V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory PdfPrinter$Callback.implement($PdfPrinter$Callback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<PdfPrinter$Callback>();
  }
}

extension PdfPrinter$Callback$$Methods on PdfPrinter$Callback {
  static final _id_onSuccess = PdfPrinter$Callback._class.instanceMethodId(
    r'onSuccess',
    r'(Ljava/lang/String;)V',
  );

  static final _onSuccess =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onSuccess(filePath: kotlin.String): kotlin.Unit`
  void onSuccess(jni$_.JString string) {
    final _$string = string.reference;
    _onSuccess(
      reference.pointer,
      _id_onSuccess.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_onFailure = PdfPrinter$Callback._class.instanceMethodId(
    r'onFailure',
    r'()V',
  );

  static final _onFailure =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onFailure(): kotlin.Unit`
  void onFailure() {
    _onFailure(reference.pointer, _id_onFailure.pointer).check();
  }
}

abstract base mixin class $PdfPrinter$Callback {
  factory $PdfPrinter$Callback({
    required void Function(jni$_.JString string) onSuccess,
    core$_.bool onSuccess$async,
    required void Function() onFailure,
    core$_.bool onFailure$async,
  }) = _$PdfPrinter$Callback;

  void onSuccess(jni$_.JString string);
  core$_.bool get onSuccess$async => false;
  void onFailure();
  core$_.bool get onFailure$async => false;
}

final class _$PdfPrinter$Callback with $PdfPrinter$Callback {
  _$PdfPrinter$Callback({
    required void Function(jni$_.JString string) onSuccess,
    this.onSuccess$async = false,
    required void Function() onFailure,
    this.onFailure$async = false,
  }) : _onSuccess = onSuccess,
       _onFailure = onFailure;

  final void Function(jni$_.JString string) _onSuccess;
  final core$_.bool onSuccess$async;
  final void Function() _onFailure;
  final core$_.bool onFailure$async;

  void onSuccess(jni$_.JString string) {
    return _onSuccess(string);
  }

  void onFailure() {
    return _onFailure();
  }
}

final class $PdfPrinter$Callback$Type$
    extends jni$_.JType<PdfPrinter$Callback> {
  @jni$_.internal
  const $PdfPrinter$Callback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/PdfPrinter$Callback;';
}

/// from: `com.example.native_pdf_engine.PdfPrinter`
extension type PdfPrinter._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/PdfPrinter',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfPrinter> type = $PdfPrinter$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Landroid/print/PrintAttributes;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.print.PrintAttributes printAttributes)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PdfPrinter(printattributes$_.PrintAttributes printAttributes) {
    final _$printAttributes = printAttributes.reference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$printAttributes.pointer,
    ).object<PdfPrinter>();
  }
}

extension PdfPrinter$$Methods on PdfPrinter {
  static final _id_print = PdfPrinter._class.instanceMethodId(
    r'print',
    r'(Landroid/print/PrintDocumentAdapter;Ljava/io/File;Ljava/lang/String;Lcom/example/native_pdf_engine/PdfPrinter$Callback;)V',
  );

  static final _print =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun print(printAdapter: android.print.PrintDocumentAdapter, path: java.io.File, fileName: kotlin.String, callback: com.example.native_pdf_engine.PdfPrinter.Callback): kotlin.Unit`
  void print(
    printdocumentadapter$_.PrintDocumentAdapter printDocumentAdapter,
    file$_.File file,
    jni$_.JString string,
    PdfPrinter$Callback callback,
  ) {
    final _$printDocumentAdapter = printDocumentAdapter.reference;
    final _$file = file.reference;
    final _$string = string.reference;
    final _$callback = callback.reference;
    _print(
      reference.pointer,
      _id_print.pointer,
      _$printDocumentAdapter.pointer,
      _$file.pointer,
      _$string.pointer,
      _$callback.pointer,
    ).check();
  }

  static final _id_prepareWebView = PdfPrinter._class.instanceMethodId(
    r'prepareWebView',
    r'(Landroid/webkit/WebView;Ljava/io/File;Ljava/lang/String;Lcom/example/native_pdf_engine/PdfPrinter$Callback;)V',
  );

  static final _prepareWebView =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun prepareWebView(webView: android.webkit.WebView, path: java.io.File, fileName: kotlin.String, callback: com.example.native_pdf_engine.PdfPrinter.Callback): kotlin.Unit`
  void prepareWebView(
    webview$_.WebView webView,
    file$_.File file,
    jni$_.JString string,
    PdfPrinter$Callback callback,
  ) {
    final _$webView = webView.reference;
    final _$file = file.reference;
    final _$string = string.reference;
    final _$callback = callback.reference;
    _prepareWebView(
      reference.pointer,
      _id_prepareWebView.pointer,
      _$webView.pointer,
      _$file.pointer,
      _$string.pointer,
      _$callback.pointer,
    ).check();
  }

  static final _id_printFromWebView = PdfPrinter._class.instanceMethodId(
    r'printFromWebView',
    r'(Landroid/webkit/WebView;Ljava/io/File;Ljava/lang/String;Lcom/example/native_pdf_engine/PdfPrinter$Callback;)V',
  );

  static final _printFromWebView =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun printFromWebView(webView: android.webkit.WebView, path: java.io.File, fileName: kotlin.String, callback: com.example.native_pdf_engine.PdfPrinter.Callback): kotlin.Unit`
  void printFromWebView(
    webview$_.WebView webView,
    file$_.File file,
    jni$_.JString string,
    PdfPrinter$Callback callback,
  ) {
    final _$webView = webView.reference;
    final _$file = file.reference;
    final _$string = string.reference;
    final _$callback = callback.reference;
    _printFromWebView(
      reference.pointer,
      _id_printFromWebView.pointer,
      _$webView.pointer,
      _$file.pointer,
      _$string.pointer,
      _$callback.pointer,
    ).check();
  }
}

final class $PdfPrinter$Type$ extends jni$_.JType<PdfPrinter> {
  @jni$_.internal
  const $PdfPrinter$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/native_pdf_engine/PdfPrinter;';
}
